name: 'Set up environment'
description: 'Sets up environment by installing dependencies and creating a build'

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/yarn2-install@v3

    - uses: myparcelnl/actions/cache-nx@v3

    - name: 'Build packages'
      shell: bash
      run: |
        nx run-many \
          --parallel \
          --target=build \
          --output-style=static
