approvedGitRepositories:
  - "**"

compressionLevel: 0

enableGlobalCache: true

enableScripts: true

ignorePath: true

nmSelfReferences: false

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmRegistries:
  //registry.npmjs.org/:
    npmAuthToken: "${NPM_TOKEN:-invalid}"
