compressionLevel: 0

enableGlobalCache: true

nmSelfReferences: false

nodeLinker: node-modules

npmRegistries:
  //registry.npmjs.org/:
    npmAuthToken: "${NPM_TOKEN:-invalid}"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
