import {
  runActionContainerTest,
  runButtonTest,
  runCheckboxInputTest,
  runColTest,
  runCurrencyInputTest,
  runDropDownButtonTest,
  runFormGroupTest,
  runHeadingTest,
  runIconTest,
  runImageTest,
  runLinkTest,
  runModalTest,
  runMultiCheckboxTest,
  runMultiRadioTest,
  runNotificationTest,
  runNumberInputTest,
  runPlainWrapperTest,
  runRadioInputTest,
  runRowTest,
  runSelectInputTest,
  runTabNavButtonTest,
  runTableColTest,
  runTableRowTest,
  runTableTest,
  runTextInputTest,
  runToggleInputTest,
} from '../components';
import {AdminComponentName} from '@myparcel-pdk/common/src';
import {Component} from 'vue';

export type AdminComponentTest = (component: Omit<Component, 'props'>) => void;

export const testMap: Record<AdminComponentName, AdminComponentTest> = {
  PdkBox: runActionContainerTest,
  PdkConceptBoxWrapper: runActionContainerTest,
  PdkShipmentLabelWrapper: runActionContainerTest,

  PdkButtonGroup: runPlainWrapperTest,
  PdkPluginSettingsWrapper: runPlainWrapperTest,
  PdkTabNavButtonWrapper: runPlainWrapperTest,
  PdkTabNavContentWrapper: runPlainWrapperTest,

  PdkButton: runButtonTest,
  PdkCheckboxInput: runCheckboxInputTest,
  PdkCol: runColTest,
  PdkCurrencyInput: runCurrencyInputTest,
  PdkDropdownButton: runDropDownButtonTest,
  PdkFormGroup: runFormGroupTest,
  PdkHeading: runHeadingTest,
  PdkIcon: runIconTest,
  PdkImage: runImageTest,
  PdkLink: runLinkTest,
  PdkModal: runModalTest,
  PdkMultiCheckbox: runMultiCheckboxTest,
  PdkMultiRadio: runMultiRadioTest,
  PdkNotification: runNotificationTest,
  PdkNumberInput: runNumberInputTest,
  PdkRadioInput: runRadioInputTest,
  PdkRow: runRowTest,
  PdkSelectInput: runSelectInputTest,
  PdkTabNavButton: runTabNavButtonTest,
  PdkTable: runTableTest,
  PdkTableCol: runTableColTest,
  PdkTableRow: runTableRowTest,
  PdkTextInput: runTextInputTest,
  PdkToggleInput: runToggleInputTest,
};
