import {PdkContextObject} from '@myparcel/pdk-frontend';

export const context: PdkContextObject = {
  orderIdentifier: '',
  global: {
    baseUrl: 'http://localhost',
    bootstrapId: 'myparcel-pdk-bootstrap',
    event: '',
    pluginSettings: {
      carrier: [],
      order: {
        ignoreOrderStatuses: 'true',
        orderStatusMail: 'true',
        sendNotificationAfter: 'true',
        sendOrderStateForDigitalStamps: 1,
        statusOnLabelCreate: 'true',
        statusWhenDelivered: 'true',
        statusWhenLabelScanned: 'true',
      },
      checkout: {
        showPriceSurcharge: true,
        // deliveryOptionsDisplay: true,
        // deliveryOptionsPosition: 'deliveryOptionsPosition',
        pickupLocationsDefaultView: 'pickupLocationsDefaultView',
        // priceType: 'priceType',
        // showDeliveryDay: true,
      },
      customs: {
        countryOfOrigin: 'countryOfOrigin',
        customsCode: 'customsCode',
        packageContents: 'packageContents',
      },
      general: {
        apiKey: '',
        barcodeInNote: true,
        conceptShipments: true,
        enableApiLogging: true,
        orderMode: true,
        priceType: 'surcharge',
        processDirectly: true,
        shareCustomerInformation: true,
        showDeliveryDay: true,
        trackTraceEmail: true,
        trackTraceMyAccount: true,
        useSeparateAddressFields: false,
      },
      label: {
        defaultPosition: 'a4',
        labelDescription: '',
        labelOpenDownload: 'download',
        labelSize: '',
        promptPosition: true,
      },
    },
    mode: 'development',
    translations: {},
    endpoints: {
      exportOrder: {
        body: '',
        headers: {},
        method: 'GET',
        path: '',
        parameters: {
          action: 'exportOrder',
        },
        queryString: '',
      },
      exportPrintOrder: {
        body: '',
        headers: {},
        method: 'GET',
        path: '',
        parameters: {
          action: 'exportPrintOrder',
        },
        queryString: '',
      },
      getOrder: {
        body: '',
        headers: {},
        method: 'GET',
        path: '',
        parameters: {
          action: 'getOrder',
        },
        queryString: '',
      },
    },
  },
  orderData: [
    {
      externalIdentifier: '3',
      // customsDeclaration: {
      //   contents: 1,
      //   invoice: undefined,
      //   items: [],
      //   weight: 0,
      // },
      deliveryOptions: {
        carrier: undefined,
        date: undefined,
        deliveryType: undefined,
        labelAmount: 1,
        packageType: 'package',
        pickupLocation: undefined,
        shipmentOptions: {
          ageCheck: undefined,
          insurance: undefined,
          labelDescription: undefined,
          largeFormat: undefined,
          onlyRecipient: undefined,
          return: undefined,
          sameDayDelivery: undefined,
          signature: undefined,
        },
      },
      recipient: {
        cc: 'US',
        city: 'Miami',
        company: 'My Company',
        email: 'admin@prestashop.dev.myparcel.nl',
        fullStreet: '16, Main street 2nd floor',
        number: undefined,
        numberSuffix: undefined,
        person: 'John DOE',
        phone: '0102030405',
        postalCode: '33133',
        region: 'Florida',
        state: undefined,
        street: '16, Main street 2nd floor',
        streetAdditionalInfo: undefined,
      },
      sender: {
        cc: undefined,
        city: undefined,
        company: undefined,
        email: undefined,
        fullStreet: undefined,
        number: undefined,
        numberSuffix: undefined,
        person: undefined,
        phone: undefined,
        postalCode: undefined,
        region: undefined,
        state: undefined,
        street: undefined,
        streetAdditionalInfo: undefined,
      },
      shipments: [
        {
          id: 3,
          referenceIdentifier: '3',
          externalIdentifier: undefined,
          apiKey: undefined,
          barcode: undefined,
          carrier: undefined,
          collectionContact: undefined,
          created: undefined,
          createdBy: undefined,
          customsDeclaration: undefined,
          delayed: undefined,
          delivered: undefined,
          deliveryOptions: {
            carrier: undefined,
            date: undefined,
            deliveryType: undefined,
            labelAmount: 1,
            packageType: 'package',
            pickupLocation: undefined,
            shipmentOptions: {
              ageCheck: undefined,
              insurance: undefined,
              labelDescription: undefined,
              largeFormat: undefined,
              onlyRecipient: undefined,
              return: undefined,
              sameDayDelivery: undefined,
              signature: undefined,
            },
          },
          dropOffPoint: undefined,
          isReturn: undefined,
          linkConsumerPortal: undefined,
          modified: undefined,
          modifiedBy: undefined,
          multiCollo: false,
          multiColloMainShipmentId: undefined,
          partnerTrackTraces: undefined,
          physicalProperties: {
            height: undefined,
            length: undefined,
            weight: 0,
            width: undefined,
          },
          recipient: {
            cc: 'US',
            city: 'Miami',
            fullStreet: '16, Main street 2nd floor',
            number: undefined,
            numberSuffix: undefined,
            postalCode: '33133',
            region: 'Florida',
            state: undefined,
            street: '16, Main street 2nd floor',
            streetAdditionalInfo: undefined,
            email: 'admin@prestashop.dev.myparcel.nl',
            phone: '0102030405',
            person: 'John DOE',
            company: 'My Company',
          },
          sender: {
            cc: undefined,
            city: undefined,
            company: undefined,
            email: undefined,
            fullStreet: undefined,
            number: undefined,
            numberSuffix: undefined,
            person: undefined,
            phone: undefined,
            postalCode: undefined,
            region: undefined,
            state: undefined,
            street: undefined,
            streetAdditionalInfo: undefined,
          },
          shopId: undefined,
          status: undefined,
          updated: undefined,
        },
      ],
    },
  ],
};
