/* eslint-disable @typescript-eslint/no-magic-numbers */
import {CARRIERS, DELIVERY_TYPES} from '@myparcel/sdk';
import {Plugin} from '@myparcel-pdk/common';

// eslint-disable-next-line max-lines-per-function
export const useDemoOrderData = (): Plugin.ModelContextOrderDataContext[] => [
  {
    externalIdentifier: '3',
    customsDeclaration: {
      contents: 1,
      invoice: undefined,
      items: [],
      weight: 0,
    },
    deliveryOptions: {
      carrier: undefined,
      date: undefined,
      deliveryType: undefined,
      labelAmount: 1,
      packageType: 'package',
      pickupLocation: undefined,
      shipmentOptions: {
        ageCheck: undefined,
        insurance: undefined,
        labelDescription: undefined,
        largeFormat: undefined,
        onlyRecipient: undefined,
        return: undefined,
        sameDayDelivery: undefined,
        signature: undefined,
      },
    },

    recipient: {
      boxNumber: undefined,
      cc: 'US',
      city: 'Miami',
      fullStreet: '16, Main street 2nd floor',
      number: undefined,
      numberSuffix: undefined,
      postalCode: '33133',
      region: 'Florida',
      state: undefined,
      street: '16, Main street 2nd floor',
      streetAdditionalInfo: undefined,
      email: 'admin@prestashop.dev.myparcel.nl',
      phone: '0102030405',
      person: 'John DOE',
      company: 'My Company',
    },

    sender: {
      boxNumber: undefined,
      cc: undefined,
      city: undefined,
      fullStreet: undefined,
      number: undefined,
      numberSuffix: undefined,
      postalCode: undefined,
      region: undefined,
      state: undefined,
      street: undefined,
      streetAdditionalInfo: undefined,
      email: undefined,
      phone: undefined,
      person: undefined,
      company: undefined,
    },

    shipments: [
      {
        apiKey: undefined,
        barcode: undefined,
        carrier: undefined,
        collectionContact: undefined,
        created: undefined,
        createdBy: undefined,
        customsDeclaration: undefined,
        delayed: undefined,
        delivered: undefined,
        deliveryOptions: {
          carrier: undefined,
          date: undefined,
          deliveryType: undefined,
          labelAmount: 1,
          packageType: 'package',
          pickupLocation: undefined,
          shipmentOptions: {
            ageCheck: undefined,
            insurance: undefined,
            labelDescription: undefined,
            largeFormat: undefined,
            onlyRecipient: undefined,
            return: undefined,
            sameDayDelivery: undefined,
            signature: undefined,
          },
        },

        dropOffPoint: undefined,
        externalIdentifier: undefined,
        id: 4,
        isReturn: false,
        linkConsumerPortal: undefined,
        modified: undefined,
        modifiedBy: undefined,
        multiCollo: false,
        multiColloMainShipmentId: undefined,
        partnerTrackTraces: [],
        physicalProperties: {
          height: undefined,
          length: undefined,
          weight: 0,
          width: undefined,
        },
        recipient: {
          boxNumber: undefined,
          cc: 'US',
          city: 'Miami',
          fullStreet: '16, Main street 2nd floor',
          number: undefined,
          numberSuffix: undefined,
          postalCode: '33133',
          region: 'Florida',
          state: undefined,
          street: '16, Main street 2nd floor',
          streetAdditionalInfo: undefined,
          email: 'admin@prestashop.dev.myparcel.nl',
          phone: '0102030405',
          person: 'John DOE',
          company: 'My Company',
        },

        referenceIdentifier: '4',
        sender: {
          boxNumber: undefined,
          cc: undefined,
          city: undefined,
          fullStreet: undefined,
          number: undefined,
          numberSuffix: undefined,
          postalCode: undefined,
          region: undefined,
          state: undefined,
          street: undefined,
          streetAdditionalInfo: undefined,
          email: undefined,
          phone: undefined,
          person: undefined,
          company: undefined,
        },

        shopId: undefined,
        status: undefined,
        updated: undefined,
      },
    ],
  },
  {
    externalIdentifier: '4',
    customsDeclaration: {
      contents: 1,
      invoice: undefined,
      items: [],
      weight: 0,
    },
    deliveryOptions: {
      carrier: undefined,
      date: undefined,
      deliveryType: undefined,
      labelAmount: 1,
      packageType: 'package',
      pickupLocation: undefined,
      shipmentOptions: {
        ageCheck: undefined,
        insurance: undefined,
        labelDescription: undefined,
        largeFormat: undefined,
        onlyRecipient: undefined,
        return: undefined,
        sameDayDelivery: undefined,
        signature: undefined,
      },
    },

    recipient: {
      boxNumber: undefined,
      cc: 'US',
      city: 'Miami',
      fullStreet: '16, Main street 2nd floor',
      number: undefined,
      numberSuffix: undefined,
      postalCode: '33133',
      region: 'Florida',
      state: undefined,
      street: '16, Main street 2nd floor',
      streetAdditionalInfo: undefined,
      email: 'admin@prestashop.dev.myparcel.nl',
      phone: '0102030405',
      person: 'John DOE',
      company: 'My Company',
    },

    sender: {
      boxNumber: undefined,
      cc: undefined,
      city: undefined,
      fullStreet: undefined,
      number: undefined,
      numberSuffix: undefined,
      postalCode: undefined,
      region: undefined,
      state: undefined,
      street: undefined,
      streetAdditionalInfo: undefined,
      email: undefined,
      phone: undefined,
      person: undefined,
      company: undefined,
    },

    shipments: [
      {
        apiKey: 'undefined',
        barcode: 'undefined',
        carrier: {
          id: CARRIERS.POSTNL.ID,
          human: CARRIERS.POSTNL.HUMAN,
          name: CARRIERS.POSTNL.NAME,
          label: 'PostNl MyPa',
          isDefault: true,
          primary: true,
          subscriptionId: 12345,
          options: [],
          returnOptions: [],
          type: 'carrier',
          optional: false,
        },
        collectionContact: 'undefined',
        created: {
          date: '2021-09-15 14:00:00.000000',
        },
        createdBy: undefined,
        customsDeclaration: undefined,
        delayed: false,
        delivered: false,
        deliveryOptions: {
          carrier: CARRIERS.POSTNL.NAME,
          date: {
            date: '2021-09-15 14:00:00.000000',
          },
          deliveryType: DELIVERY_TYPES.STANDARD.NAME,
          labelAmount: 1,
          packageType: 'package',
          pickupLocation: undefined,
          shipmentOptions: {
            ageCheck: false,
            insurance: undefined,
            labelDescription: 'text',
            largeFormat: false,
            onlyRecipient: false,
            return: false,
            sameDayDelivery: false,
            signature: false,
          },
        },

        dropOffPoint: undefined,
        externalIdentifier: undefined,
        id: 4,
        isReturn: false,
        linkConsumerPortal: undefined,
        modified: undefined,
        modifiedBy: undefined,
        multiCollo: false,
        multiColloMainShipmentId: undefined,
        partnerTrackTraces: [],
        physicalProperties: {
          height: undefined,
          length: undefined,
          weight: 0,
          width: undefined,
        },
        recipient: {
          boxNumber: undefined,
          cc: 'US',
          city: 'Miami',
          fullStreet: '16, Main street 2nd floor',
          number: undefined,
          numberSuffix: undefined,
          postalCode: '33133',
          region: 'Florida',
          state: undefined,
          street: '16, Main street 2nd floor',
          streetAdditionalInfo: undefined,
          email: 'admin@prestashop.dev.myparcel.nl',
          phone: '0102030405',
          person: 'John DOE',
          company: 'My Company',
        },

        referenceIdentifier: '4',
        sender: {
          boxNumber: undefined,
          cc: undefined,
          city: undefined,
          fullStreet: undefined,
          number: undefined,
          numberSuffix: undefined,
          postalCode: undefined,
          region: undefined,
          state: undefined,
          street: undefined,
          streetAdditionalInfo: undefined,
          email: undefined,
          phone: undefined,
          person: undefined,
          company: undefined,
        },

        shopId: undefined,
        status: undefined,
        updated: undefined,
      },
    ],
  },
];
