import {
  DefaultBox,
  DefaultButton,
  DefaultButtonGroup,
  DefaultCheckboxGroup,
  DefaultCheckboxInput,
  DefaultCodeEditor,
  DefaultCol,
  DefaultCurrencyInput,
  DefaultDropdownButton,
  DefaultFormGroup,
  DefaultHeading,
  DefaultIcon,
  DefaultImage,
  DefaultLink,
  DefaultModal,
  DefaultMultiSelectInput,
  DefaultNotification,
  DefaultNumberInput,
  DefaultRadioInput,
  DefaultRow,
  DefaultSelectInput,
  DefaultSettingsDivider,
  DefaultTabNavButton,
  DefaultTable,
  DefaultTableCol,
  DefaultTableRow,
  DefaultTextArea,
  DefaultTextInput,
  DefaultToggleInput,
} from '../components';
import {executePdkComponentTests} from '@myparcel-pdk/admin-component-tests';

executePdkComponentTests({
  PdkBox: DefaultBox,
  PdkButton: DefaultButton,
  PdkButtonGroup: DefaultButtonGroup,
  PdkCheckboxGroup: DefaultCheckboxGroup,
  PdkCheckboxInput: DefaultCheckboxInput,
  PdkCodeEditor: DefaultCodeEditor,
  PdkCol: DefaultCol,
  PdkCurrencyInput: DefaultCurrencyInput,
  PdkDropdownButton: DefaultDropdownButton,
  PdkFormGroup: DefaultFormGroup,
  PdkHeading: DefaultHeading,
  PdkIcon: DefaultIcon,
  PdkImage: DefaultImage,
  PdkLink: DefaultLink,
  PdkModal: DefaultModal,
  PdkMultiSelectInput: DefaultMultiSelectInput,
  PdkNotification: DefaultNotification,
  PdkNumberInput: DefaultNumberInput,
  PdkRadioInput: DefaultRadioInput,
  PdkRow: DefaultRow,
  PdkSelectInput: DefaultSelectInput,
  PdkSettingsDivider: DefaultSettingsDivider,
  PdkTabNavButton: DefaultTabNavButton,
  PdkTable: DefaultTable,
  PdkTableCol: DefaultTableCol,
  PdkTableRow: DefaultTableRow,
  PdkTextArea: DefaultTextArea,
  PdkTextInput: DefaultTextInput,
  PdkToggleInput: DefaultToggleInput,
});
