import {executePdkComponentTests} from '@myparcel-pdk/admin-component-tests';
import {
  DefaultBox,
  DefaultButton,
  DefaultButtonGroup,
  DefaultCheckboxGroup,
  DefaultCheckboxInput,
  DefaultCodeEditor,
  DefaultCol,
  DefaultCurrencyInput,
  DefaultDropdownButton,
  DefaultFormGroup,
  DefaultHeading,
  DefaultIcon,
  DefaultImage,
  DefaultLink,
  DefaultModal,
  DefaultMultiSelectInput,
  DefaultNotification,
  DefaultNumberInput,
  DefaultRadioInput,
  DefaultRow,
  DefaultSelectInput,
  DefaultSettingsDivider,
  DefaultTabNavButton,
  DefaultTable,
  DefaultTableCol,
  DefaultTableRow,
  DefaultTextArea,
  DefaultTextInput,
  DefaultToggleInput,
  DefaultBadge,
  DefaultDropOffInput,
  DefaultLoader,
  DefaultRadioGroup,
  DefaultTimeInput,
} from '../components';

executePdkComponentTests({
  Badge: DefaultBadge,
  Box: DefaultBox,
  Button: DefaultButton,
  ButtonGroup: DefaultButtonGroup,
  CheckboxGroup: DefaultCheckboxGroup,
  CheckboxInput: DefaultCheckboxInput,
  CodeEditor: DefaultCodeEditor,
  Col: DefaultCol,
  CurrencyInput: DefaultCurrencyInput,
  DropOffInput: DefaultDropOffInput,
  DropdownButton: DefaultDropdownButton,
  FormGroup: DefaultFormGroup,
  Heading: DefaultHeading,
  Icon: DefaultIcon,
  Image: DefaultImage,
  Link: DefaultLink,
  Loader: DefaultLoader,
  Modal: DefaultModal,
  MultiSelectInput: DefaultMultiSelectInput,
  Notification: DefaultNotification,
  NumberInput: DefaultNumberInput,
  RadioGroup: DefaultRadioGroup,
  RadioInput: DefaultRadioInput,
  Row: DefaultRow,
  SelectInput: DefaultSelectInput,
  SettingsDivider: DefaultSettingsDivider,
  TabNavButton: DefaultTabNavButton,
  Table: DefaultTable,
  TableCol: DefaultTableCol,
  TableRow: DefaultTableRow,
  TextArea: DefaultTextArea,
  TextInput: DefaultTextInput,
  TimeInput: DefaultTimeInput,
  ToggleInput: DefaultToggleInput,
});
