/* eslint-disable @typescript-eslint/no-magic-numbers */
import {AdminContextObject} from '@myparcel-pdk/frontend-core/src';
import {BackendEndpoint} from '@myparcel-pdk/common/src';
import {CarrierName} from '@myparcel/constants';
import translations from './translations/en.json';

export const context: AdminContextObject = {
  orderIdentifier: '',
  global: {
    appInfo: {
      title: 'Admin Demo',
      version: '1.0.0',
      name: 'admin-demo',
      path: '/admin-demo/',
      url: 'https://admin-demo.dev.myparcel.nl',
    },
    baseUrl: 'http://localhost',
    bootId: 'myparcel-pdk-boot',
    endpoints: Object.keys(BackendEndpoint).reduce(
      (acc, key) => ({
        ...acc,
        [key]: {
          body: '',
          headers: [],
          method: '',
          parameters: {
            action: key,
          },
          path: '',
          property: '',
        },
      }),
      {} as AdminContextObject['global']['endpoints'],
    ),
    event: '',
    language: 'en',
    mode: 'development',
    translations,
  },

  pluginSettingsView: {
    general: {
      id: 'general',
      title: 'settings_view_general_title',
      description: 'settings_view_general_description',
      elements: [
        {
          name: 'apiLogging',
          $component: 'ToggleInput',
          label: 'settings_general_api_logging',
          description: 'settings_general_api_logging_description',
        },
        {
          name: 'shareCustomerInformation',
          $component: 'ToggleInput',
          label: 'settings_general_share_customer_information',
          description: 'settings_general_share_customer_information_description',
        },
        {
          name: 'conceptShipments',
          $component: 'ToggleInput',
          label: 'settings_general_concept_shipments',
          description: 'settings_general_concept_shipments_description',
        },
        {
          name: 'orderMode',
          $component: 'ToggleInput',
          label: 'settings_general_order_mode',
          description: 'settings_general_order_mode_description',
        },
        {
          name: 'trackTraceInEmail',
          $component: 'ToggleInput',
          label: 'settings_general_track_trace_in_email',
          description: 'settings_general_track_trace_in_email_description',
        },
        {
          name: 'trackTraceInAccount',
          $component: 'ToggleInput',
          label: 'settings_general_track_trace_in_account',
          description: 'settings_general_track_trace_in_account_description',
        },
        {
          name: 'barcodeInNote',
          $component: 'ToggleInput',
          label: 'settings_general_barcode_in_note',
          description: 'settings_general_barcode_in_note_description',
        },
        {
          name: 'processDirectly',
          $component: 'ToggleInput',
          label: 'settings_general_process_directly',
          description: 'settings_general_process_directly_description',
        },
      ],
      children: null,
    },
    order: {
      id: 'order',
      title: 'settings_view_order_title',
      description: 'settings_view_order_description',
      elements: [
        {
          name: 'statusOnLabelCreate',
          $component: 'SelectInput',
          options: [
            {value: -1, label: 'settings_none'},
            {value: 'wc-pending', label: 'Wachtend op betaling'},
            {value: 'wc-processing', label: 'In behandeling'},
            {value: 'wc-on-hold', label: 'In de wacht'},
            {value: 'wc-completed', label: 'Afgerond'},
            {value: 'wc-cancelled', label: 'Geannuleerd'},
            {value: 'wc-refunded', label: 'Terugbetaald'},
            {value: 'wc-failed', label: 'Mislukt'},
          ],
          label: 'settings_order_status_on_label_create',
          description: 'settings_order_status_on_label_create_description',
        },
        {
          name: 'statusWhenLabelScanned',
          $component: 'SelectInput',
          options: [
            {value: -1, label: 'settings_none'},
            {value: 'wc-pending', label: 'Wachtend op betaling'},
            {value: 'wc-processing', label: 'In behandeling'},
            {value: 'wc-on-hold', label: 'In de wacht'},
            {value: 'wc-completed', label: 'Afgerond'},
            {value: 'wc-cancelled', label: 'Geannuleerd'},
            {value: 'wc-refunded', label: 'Terugbetaald'},
            {value: 'wc-failed', label: 'Mislukt'},
          ],
          label: 'settings_order_status_when_label_scanned',
          description: 'settings_order_status_when_label_scanned_description',
        },
        {
          name: 'statusWhenDelivered',
          $component: 'SelectInput',
          options: [
            {value: -1, label: 'settings_none'},
            {value: 'wc-pending', label: 'Wachtend op betaling'},
            {value: 'wc-processing', label: 'In behandeling'},
            {value: 'wc-on-hold', label: 'In de wacht'},
            {value: 'wc-completed', label: 'Afgerond'},
            {value: 'wc-cancelled', label: 'Geannuleerd'},
            {value: 'wc-refunded', label: 'Terugbetaald'},
            {value: 'wc-failed', label: 'Mislukt'},
          ],
          label: 'settings_order_status_when_delivered',
          description: 'settings_order_status_when_delivered_description',
        },
        {
          name: 'ignoreOrderStatuses',
          $component: 'CheckboxInput',
          options: [
            {value: -1, label: 'settings_none'},
            {value: 'wc-pending', label: 'Wachtend op betaling'},
            {value: 'wc-processing', label: 'In behandeling'},
            {value: 'wc-on-hold', label: 'In de wacht'},
            {value: 'wc-completed', label: 'Afgerond'},
            {value: 'wc-cancelled', label: 'Geannuleerd'},
            {value: 'wc-refunded', label: 'Terugbetaald'},
            {value: 'wc-failed', label: 'Mislukt'},
          ],
          label: 'settings_order_ignore_order_statuses',
          description: 'settings_order_ignore_order_statuses_description',
        },
        {
          name: 'orderStatusMail',
          $component: 'ToggleInput',
          label: 'settings_order_order_status_mail',
          description: 'settings_order_order_status_mail_description',
        },
        {
          name: 'sendNotificationAfter',
          $component: 'SelectInput',
          options: [],
          label: 'settings_order_send_notification_after',
          description: 'settings_order_send_notification_after_description',
        },
        {
          name: 'sendOrderStateForDigitalStamp',
          $component: 'ToggleInput',
          label: 'settings_order_send_order_state_for_digital_stamp',
          description: 'settings_order_send_order_state_for_digital_stamp_description',
        },
        {
          name: 'saveCustomerAddress',
          $component: 'ToggleInput',
          label: 'settings_order_save_customer_address',
          description: 'settings_order_save_customer_address_description',
        },
        {
          name: 'emptyParcelWeight',
          $component: 'NumberInput',
          label: 'settings_order_empty_parcel_weight',
          description: 'settings_order_empty_parcel_weight_description',
        },
      ],
      children: null,
    },
    label: {
      id: 'label',
      title: 'settings_view_label_title',
      description: 'settings_view_label_description',
      elements: [
        {
          name: 'description',
          $component: 'TextInput',
          label: 'settings_label_description',
          description: 'settings_label_description_description',
        },
        {
          name: 'format',
          $component: 'SelectInput',
          options: [
            {value: 'A4', label: 'settings_label_format_option_a4'},
            {value: 'A6', label: 'settings_label_format_option_a6'},
          ],
          label: 'settings_label_format',
          description: 'settings_label_format_description',
        },
        {
          name: 'position',
          $component: 'SelectInput',
          options: [
            {value: 1, label: 'settings_label_position_option_1'},
            {value: 2, label: 'settings_label_position_option_2'},
            {value: 3, label: 'settings_label_position_option_3'},
            {value: 4, label: 'settings_label_position_option_4'},
          ],
          label: 'settings_label_position',
          description: 'settings_label_position_description',
        },
        {
          name: 'output',
          $component: 'SelectInput',
          options: [
            {value: 'open', label: 'settings_label_output_option_open'},
            {value: 'download', label: 'settings_label_output_option_download'},
          ],
          label: 'settings_label_output',
          description: 'settings_label_output_description',
        },
        {
          name: 'prompt',
          $component: 'ToggleInput',
          label: 'settings_label_prompt',
          description: 'settings_label_prompt_description',
        },
      ],
      children: null,
    },
    customs: {
      id: 'customs',
      title: 'settings_view_customs_title',
      description: 'settings_view_customs_description',
      elements: [
        {
          name: 'packageContents',
          $component: 'SelectInput',
          options: [
            {value: 1, label: 'customs_package_contents_commercial_goods'},
            {value: 2, label: 'customs_package_contents_commercial_samples'},
            {value: 3, label: 'customs_package_contents_documents'},
            {value: 4, label: 'customs_package_contents_gifts'},
            {value: 5, label: 'customs_package_contents_return_shipment'},
          ],
          label: 'settings_customs_package_contents',
          description: 'settings_customs_package_contents_description',
        },
        {
          name: 'customsCode',
          $component: 'TextInput',
          label: 'settings_customs_customs_code',
          description: 'settings_customs_customs_code_description',
        },
        {
          name: 'countryOfOrigin',
          $component: 'SelectInput',
          options: [
            {value: 'AC', label: 'AC'},
            {value: 'AD', label: 'AD'},
            {value: 'AE', label: 'AE'},
            {value: 'AF', label: 'AF'},
            {value: 'AG', label: 'AG'},
            {value: 'AI', label: 'AI'},
            {value: 'AL', label: 'AL'},
            {value: 'AM', label: 'AM'},
            {value: 'AN', label: 'AN'},
            {value: 'AO', label: 'AO'},
            {value: 'AQ', label: 'AQ'},
            {value: 'AR', label: 'AR'},
            {value: 'AS', label: 'AS'},
            {value: 'AT', label: 'AT'},
            {value: 'AU', label: 'AU'},
            {value: 'AW', label: 'AW'},
            {value: 'AX', label: 'AX'},
            {value: 'AZ', label: 'AZ'},
            {value: 'BA', label: 'BA'},
            {value: 'BB', label: 'BB'},
            {value: 'BD', label: 'BD'},
            {value: 'BE', label: 'BE'},
            {value: 'BF', label: 'BF'},
            {value: 'BG', label: 'BG'},
            {value: 'BH', label: 'BH'},
            {value: 'BI', label: 'BI'},
            {value: 'BJ', label: 'BJ'},
            {value: 'BL', label: 'BL'},
            {value: 'BM', label: 'BM'},
            {value: 'BN', label: 'BN'},
            {value: 'BO', label: 'BO'},
            {value: 'BQ', label: 'BQ'},
            {value: 'BR', label: 'BR'},
            {value: 'BS', label: 'BS'},
            {value: 'BT', label: 'BT'},
            {value: 'BV', label: 'BV'},
            {value: 'BW', label: 'BW'},
            {value: 'BY', label: 'BY'},
            {value: 'BZ', label: 'BZ'},
            {value: 'CA', label: 'CA'},
            {value: 'CC', label: 'CC'},
            {value: 'CD', label: 'CD'},
            {value: 'CF', label: 'CF'},
            {value: 'CG', label: 'CG'},
            {value: 'CH', label: 'CH'},
            {value: 'CI', label: 'CI'},
            {value: 'CK', label: 'CK'},
            {value: 'CL', label: 'CL'},
            {value: 'CM', label: 'CM'},
            {value: 'CN', label: 'CN'},
            {value: 'CO', label: 'CO'},
            {value: 'CR', label: 'CR'},
            {value: 'CU', label: 'CU'},
            {value: 'CV', label: 'CV'},
            {value: 'CW', label: 'CW'},
            {value: 'CX', label: 'CX'},
            {value: 'CY', label: 'CY'},
            {value: 'CZ', label: 'CZ'},
            {value: 'DE', label: 'DE'},
            {value: 'DG', label: 'DG'},
            {value: 'DJ', label: 'DJ'},
            {value: 'DK', label: 'DK'},
            {value: 'DM', label: 'DM'},
            {value: 'DO', label: 'DO'},
            {value: 'DZ', label: 'DZ'},
            {value: 'EA', label: 'EA'},
            {value: 'EC', label: 'EC'},
            {value: 'EE', label: 'EE'},
            {value: 'EG', label: 'EG'},
            {value: 'EH', label: 'EH'},
            {value: 'ER', label: 'ER'},
            {value: 'ES', label: 'ES'},
            {value: 'ET', label: 'ET'},
            {value: 'EZ', label: 'EZ'},
            {value: 'FI', label: 'FI'},
            {value: 'FJ', label: 'FJ'},
            {value: 'FK', label: 'FK'},
            {value: 'FM', label: 'FM'},
            {value: 'FO', label: 'FO'},
            {value: 'FR', label: 'FR'},
            {value: 'GA', label: 'GA'},
            {value: 'GB', label: 'GB'},
            {value: 'GD', label: 'GD'},
            {value: 'GE', label: 'GE'},
            {value: 'GF', label: 'GF'},
            {value: 'GG', label: 'GG'},
            {value: 'GH', label: 'GH'},
            {value: 'GI', label: 'GI'},
            {value: 'GL', label: 'GL'},
            {value: 'GM', label: 'GM'},
            {value: 'GN', label: 'GN'},
            {value: 'GP', label: 'GP'},
            {value: 'GQ', label: 'GQ'},
            {value: 'GR', label: 'GR'},
            {value: 'GS', label: 'GS'},
            {value: 'GT', label: 'GT'},
            {value: 'GU', label: 'GU'},
            {value: 'GW', label: 'GW'},
            {value: 'GY', label: 'GY'},
            {value: 'HK', label: 'HK'},
            {value: 'HM', label: 'HM'},
            {value: 'HN', label: 'HN'},
            {value: 'HR', label: 'HR'},
            {value: 'HT', label: 'HT'},
            {value: 'HU', label: 'HU'},
            {value: 'IC', label: 'IC'},
            {value: 'ID', label: 'ID'},
            {value: 'IE', label: 'IE'},
            {value: 'IL', label: 'IL'},
            {value: 'IM', label: 'IM'},
            {value: 'IN', label: 'IN'},
            {value: 'IO', label: 'IO'},
            {value: 'IQ', label: 'IQ'},
            {value: 'IR', label: 'IR'},
            {value: 'IS', label: 'IS'},
            {value: 'IT', label: 'IT'},
            {value: 'JE', label: 'JE'},
            {value: 'JM', label: 'JM'},
            {value: 'JO', label: 'JO'},
            {value: 'JP', label: 'JP'},
            {value: 'KE', label: 'KE'},
            {value: 'KG', label: 'KG'},
            {value: 'KH', label: 'KH'},
            {value: 'KI', label: 'KI'},
            {value: 'KM', label: 'KM'},
            {value: 'KN', label: 'KN'},
            {value: 'KP', label: 'KP'},
            {value: 'KR', label: 'KR'},
            {value: 'KW', label: 'KW'},
            {value: 'KY', label: 'KY'},
            {value: 'KZ', label: 'KZ'},
            {value: 'LA', label: 'LA'},
            {value: 'LB', label: 'LB'},
            {value: 'LC', label: 'LC'},
            {value: 'LI', label: 'LI'},
            {value: 'LK', label: 'LK'},
            {value: 'LR', label: 'LR'},
            {value: 'LS', label: 'LS'},
            {value: 'LT', label: 'LT'},
            {value: 'LU', label: 'LU'},
            {value: 'LV', label: 'LV'},
            {value: 'LY', label: 'LY'},
            {value: 'MA', label: 'MA'},
            {value: 'MC', label: 'MC'},
            {value: 'MD', label: 'MD'},
            {value: 'ME', label: 'ME'},
            {value: 'MF', label: 'MF'},
            {value: 'MG', label: 'MG'},
            {value: 'MH', label: 'MH'},
            {value: 'MK', label: 'MK'},
            {value: 'ML', label: 'ML'},
            {value: 'MM', label: 'MM'},
            {value: 'MN', label: 'MN'},
            {value: 'MO', label: 'MO'},
            {value: 'MP', label: 'MP'},
            {value: 'MQ', label: 'MQ'},
            {value: 'MR', label: 'MR'},
            {value: 'MS', label: 'MS'},
            {value: 'MT', label: 'MT'},
            {value: 'MU', label: 'MU'},
            {value: 'MV', label: 'MV'},
            {value: 'MW', label: 'MW'},
            {value: 'MX', label: 'MX'},
            {value: 'MY', label: 'MY'},
            {value: 'MZ', label: 'MZ'},
            {value: 'NA', label: 'NA'},
            {value: 'NC', label: 'NC'},
            {value: 'NE', label: 'NE'},
            {value: 'NF', label: 'NF'},
            {value: 'NG', label: 'NG'},
            {value: 'NI', label: 'NI'},
            {value: 'NL', label: 'NL'},
            {value: 'NO', label: 'NO'},
            {value: 'NP', label: 'NP'},
            {value: 'NR', label: 'NR'},
            {value: 'NU', label: 'NU'},
            {value: 'NZ', label: 'NZ'},
            {value: 'OM', label: 'OM'},
            {value: 'PA', label: 'PA'},
            {value: 'PE', label: 'PE'},
            {value: 'PF', label: 'PF'},
            {value: 'PG', label: 'PG'},
            {value: 'PH', label: 'PH'},
            {value: 'PK', label: 'PK'},
            {value: 'PL', label: 'PL'},
            {value: 'PM', label: 'PM'},
            {value: 'PN', label: 'PN'},
            {value: 'PR', label: 'PR'},
            {value: 'PS', label: 'PS'},
            {value: 'PT', label: 'PT'},
            {value: 'PW', label: 'PW'},
            {value: 'PY', label: 'PY'},
            {value: 'QA', label: 'QA'},
            {value: 'RE', label: 'RE'},
            {value: 'RO', label: 'RO'},
            {value: 'RS', label: 'RS'},
            {value: 'RU', label: 'RU'},
            {value: 'RW', label: 'RW'},
            {value: 'SA', label: 'SA'},
            {value: 'SB', label: 'SB'},
            {value: 'SC', label: 'SC'},
            {value: 'SD', label: 'SD'},
            {value: 'SE', label: 'SE'},
            {value: 'SG', label: 'SG'},
            {value: 'SH', label: 'SH'},
            {value: 'SI', label: 'SI'},
            {value: 'SJ', label: 'SJ'},
            {value: 'SK', label: 'SK'},
            {value: 'SL', label: 'SL'},
            {value: 'SM', label: 'SM'},
            {value: 'SN', label: 'SN'},
            {value: 'SO', label: 'SO'},
            {value: 'SR', label: 'SR'},
            {value: 'SS', label: 'SS'},
            {value: 'ST', label: 'ST'},
            {value: 'SV', label: 'SV'},
            {value: 'SX', label: 'SX'},
            {value: 'SY', label: 'SY'},
            {value: 'SZ', label: 'SZ'},
            {value: 'TA', label: 'TA'},
            {value: 'TC', label: 'TC'},
            {value: 'TD', label: 'TD'},
            {value: 'TF', label: 'TF'},
            {value: 'TG', label: 'TG'},
            {value: 'TH', label: 'TH'},
            {value: 'TJ', label: 'TJ'},
            {value: 'TK', label: 'TK'},
            {value: 'TL', label: 'TL'},
            {value: 'TM', label: 'TM'},
            {value: 'TN', label: 'TN'},
            {value: 'TO', label: 'TO'},
            {value: 'TR', label: 'TR'},
            {value: 'TT', label: 'TT'},
            {value: 'TV', label: 'TV'},
            {value: 'TW', label: 'TW'},
            {value: 'TZ', label: 'TZ'},
            {value: 'UA', label: 'UA'},
            {value: 'UG', label: 'UG'},
            {value: 'UM', label: 'UM'},
            {value: 'US', label: 'US'},
            {value: 'UY', label: 'UY'},
            {value: 'UZ', label: 'UZ'},
            {value: 'VA', label: 'VA'},
            {value: 'VC', label: 'VC'},
            {value: 'VE', label: 'VE'},
            {value: 'VG', label: 'VG'},
            {value: 'VI', label: 'VI'},
            {value: 'VN', label: 'VN'},
            {value: 'VU', label: 'VU'},
            {value: 'WF', label: 'WF'},
            {value: 'WS', label: 'WS'},
            {value: 'XC', label: 'XC'},
            {value: 'XK', label: 'XK'},
            {value: 'XL', label: 'XL'},
            {value: 'XM', label: 'XM'},
            {value: 'YE', label: 'YE'},
            {value: 'YT', label: 'YT'},
            {value: 'ZA', label: 'ZA'},
            {value: 'ZM', label: 'ZM'},
            {value: 'ZW', label: 'ZW'},
          ],
          label: 'settings_customs_country_of_origin',
          description: 'settings_customs_country_of_origin_description',
        },
      ],
      children: null,
    },
    checkout: {
      id: 'checkout',
      title: 'settings_view_checkout_title',
      description: 'settings_view_checkout_description',
      elements: [
        {
          name: 'useSeparateAddressFields',
          $component: 'ToggleInput',
          label: 'settings_checkout_use_separate_address_fields',
        },
        {
          name: 'priceType',
          $component: 'SelectInput',
          options: [
            {value: 'included', label: 'settings_checkout_price_type_option_included'},
            {value: 'excluded', label: 'settings_checkout_price_type_option_excluded'},
          ],
          label: 'settings_checkout_price_type',
          description: 'settings_checkout_price_type_description',
        },
        {name: 'emptyWeightMailbox', $component: 'NumberInput', label: 'settings_checkout_empty_weight_mailbox'},
        {name: 'emptyWeightPackage', $component: 'NumberInput', label: 'settings_checkout_empty_weight_package'},
        {
          name: 'showDeliveryDay',
          $component: 'ToggleInput',
          label: 'settings_checkout_show_delivery_day',
          description: 'settings_checkout_show_delivery_day_description',
        },
        {
          name: 'deliveryOptionsHeader',
          $component: 'TextInput',
          label: 'settings_checkout_delivery_options_header',
        },
        {
          name: 'deliveryOptionsPosition',
          $component: 'SelectInput',
          options: [
            {value: 'woocommerce_after_cart', label: 'wc_hook_woocommerce_after_cart'},
            {value: 'woocommerce_after_cart_contents', label: 'wc_hook_woocommerce_after_cart_contents'},
            {value: 'woocommerce_after_cart_table', label: 'wc_hook_woocommerce_after_cart_table'},
            {value: 'woocommerce_after_checkout_billing', label: 'wc_hook_woocommerce_after_checkout_billing'},
            {
              value: 'woocommerce_after_checkout_billing_form',
              label: 'wc_hook_woocommerce_after_checkout_billing_form',
            },
            {value: 'woocommerce_after_checkout_form', label: 'wc_hook_woocommerce_after_checkout_form'},
            {value: 'woocommerce_after_checkout_shipping', label: 'wc_hook_woocommerce_after_checkout_shipping'},
            {
              value: 'woocommerce_after_checkout_shipping_form',
              label: 'wc_hook_woocommerce_after_checkout_shipping_form',
            },
            {value: 'woocommerce_after_order_notes', label: 'wc_hook_woocommerce_after_order_notes'},
            {value: 'woocommerce_before_cart', label: 'wc_hook_woocommerce_before_cart'},
            {value: 'woocommerce_before_cart_contents', label: 'wc_hook_woocommerce_before_cart_contents'},
            {value: 'woocommerce_before_cart_table', label: 'wc_hook_woocommerce_before_cart_table'},
            {value: 'woocommerce_before_checkout_billing', label: 'wc_hook_woocommerce_before_checkout_billing'},
            {
              value: 'woocommerce_before_checkout_billing_form',
              label: 'wc_hook_woocommerce_before_checkout_billing_form',
            },
            {value: 'woocommerce_before_checkout_form', label: 'wc_hook_woocommerce_before_checkout_form'},
            {value: 'woocommerce_before_checkout_shipping', label: 'wc_hook_woocommerce_before_checkout_shipping'},
            {
              value: 'woocommerce_before_checkout_shipping_form',
              label: 'wc_hook_woocommerce_before_checkout_shipping_form',
            },
            {value: 'woocommerce_before_order_notes', label: 'wc_hook_woocommerce_before_order_notes'},
          ],
          label: 'settings_checkout_delivery_options_position',
          description: 'settings_checkout_delivery_options_position_description',
        },
      ],
      children: null,
    },

    carrier: {
      id: 'carrier',
      title: 'settings_view_carrier_title',
      description: 'settings_view_carrier_description',
      elements: null,
      children: [
        {
          id: 'postnl',
          title: 'carrier_postnl',
          description: 'settings_view_carrier_postnl_description',
          children: null,
          elements: [
            {$component: 'Heading', $slot: 'settings_carrier_export'},
            {name: 'exportInsurance', $component: 'ToggleInput', label: 'settings_carrier_export_insurance'},
            {
              name: 'exportInsuranceFromAmount',
              $component: 'NumberInput',
              $visibleWhen: {exportInsurance: true},
              label: 'settings_carrier_export_insurance_from_amount',
            },
            {
              name: 'exportInsuranceUpTo',
              $component: 'SelectInput',
              options: [
                {value: 0, label: 0},
                {value: 100, label: 100},
                {value: 250, label: 250},
                {value: 500, label: 500},
                {value: 1000, label: 1000},
                {value: 1500, label: 1500},
                {value: 2000, label: 2000},
                {value: 2500, label: 2500},
                {value: 3000, label: 3000},
                {value: 3500, label: 3500},
                {value: 4000, label: 4000},
                {value: 4500, label: 4500},
                {value: 5000, label: 5000},
              ],
              $visibleWhen: {exportInsurance: true},
              label: 'settings_carrier_export_insurance_up_to',
            },
            {
              name: 'exportInsuranceUpToBe',
              $component: 'SelectInput',
              options: [
                {value: 0, label: 0},
                {value: 100, label: 100},
                {value: 250, label: 250},
                {value: 500, label: 500},
                {value: 1000, label: 1000},
                {value: 1500, label: 1500},
                {value: 2000, label: 2000},
                {value: 2500, label: 2500},
                {value: 3000, label: 3000},
                {value: 3500, label: 3500},
                {value: 4000, label: 4000},
                {value: 4500, label: 4500},
                {value: 5000, label: 5000},
              ],
              $visibleWhen: {exportInsurance: true},
              label: 'settings_carrier_export_insurance_up_to_be',
            },
            {
              name: 'exportInsuranceUpToEu',
              $component: 'SelectInput',
              options: [
                {value: 0, label: 0},
                {value: 100, label: 100},
                {value: 250, label: 250},
                {value: 500, label: 500},
                {value: 1000, label: 1000},
                {value: 1500, label: 1500},
                {value: 2000, label: 2000},
                {value: 2500, label: 2500},
                {value: 3000, label: 3000},
                {value: 3500, label: 3500},
                {value: 4000, label: 4000},
                {value: 4500, label: 4500},
                {value: 5000, label: 5000},
              ],
              $visibleWhen: {exportInsurance: true},
              label: 'settings_carrier_export_insurance_up_to_eu',
            },
            {name: 'exportAgeCheck', $component: 'ToggleInput', label: 'settings_carrier_export_age_check'},
            {
              name: 'exportOnlyRecipient',
              $component: 'ToggleInput',
              label: 'settings_carrier_export_only_recipient',
            },
            {name: 'exportSignature', $component: 'ToggleInput', label: 'settings_carrier_export_signature'},
            {name: 'exportLargeFormat', $component: 'ToggleInput', label: 'settings_carrier_export_large_format'},
            {
              name: 'exportReturnShipments',
              $component: 'ToggleInput',
              label: 'settings_carrier_export_return_shipments',
            },
            {$component: 'Heading', $slot: 'settings_carrier_delivery_options'},
            {
              name: 'allowDeliveryOptions',
              $component: 'ToggleInput',
              label: 'settings_carrier_allow_delivery_options',
            },
            {
              name: 'allowMondayDelivery',
              $component: 'ToggleInput',
              $visibleWhen: {allowDeliveryOptions: true},
              label: 'settings_carrier_allow_monday_delivery',
            },
            {
              name: 'allowSaturdayDelivery',
              $component: 'ToggleInput',
              $visibleWhen: {allowDeliveryOptions: true},
              label: 'settings_carrier_allow_saturday_delivery',
            },
            {
              name: 'showDeliveryDay',
              $component: 'ToggleInput',
              $visibleWhen: {allowDeliveryOptions: true},
              label: 'settings_carrier_show_delivery_day',
            },
            {
              name: 'dropOffPossibilities',
              $component: 'DropOffInput',
              $visibleWhen: {allowDeliveryOptions: true},
              label: 'settings_carrier_drop_off_possibilities',
            },
            {
              name: 'defaultPackageType',
              $component: 'SelectInput',
              $visibleWhen: {allowDeliveryOptions: true},
              options: ['package', 'mailbox', 'letter', 'digital_stamp'],
              label: 'settings_carrier_default_package_type',
            },
            {
              name: 'pricePackageTypeMailbox',
              $component: 'CurrencyInput',
              $visibleWhen: {allowDeliveryOptions: true},
              label: 'settings_carrier_price_package_type_mailbox',
            },
            {
              name: 'pricePackageTypeDigitalStamp',
              $component: 'CurrencyInput',
              $visibleWhen: {allowDeliveryOptions: true},
              label: 'settings_carrier_price_package_type_digital_stamp',
            },
            {
              name: 'allowPickupLocations',
              $component: 'ToggleInput',
              $visibleWhen: {allowDeliveryOptions: true},
              label: 'settings_carrier_allow_pickup_locations',
            },
            {
              name: 'priceDeliveryTypePickup',
              $component: 'CurrencyInput',
              $visibleWhen: {allowDeliveryOptions: true, allowPickupLocations: true},
              label: 'settings_carrier_price_delivery_type_pickup',
            },
            {
              name: 'allowSignature',
              $component: 'ToggleInput',
              $visibleWhen: {allowDeliveryOptions: true},
              label: 'settings_carrier_allow_signature',
            },
            {
              name: 'priceSignature',
              $component: 'CurrencyInput',
              $visibleWhen: {allowDeliveryOptions: true, allowSignature: true},
              label: 'settings_carrier_price_signature',
            },
            {
              name: 'allowOnlyRecipient',
              $component: 'ToggleInput',
              $visibleWhen: {allowDeliveryOptions: true},
              label: 'settings_carrier_allow_only_recipient',
            },
            {
              name: 'priceOnlyRecipient',
              $component: 'CurrencyInput',
              $visibleWhen: {allowDeliveryOptions: true, allowOnlyRecipient: true},
              label: 'settings_carrier_price_only_recipient',
            },
            {
              name: 'allowMorningDelivery',
              $component: 'ToggleInput',
              $visibleWhen: {allowDeliveryOptions: true},
              label: 'settings_carrier_allow_morning_delivery',
            },
            {
              name: 'priceDeliveryTypeMorning',
              $component: 'CurrencyInput',
              $visibleWhen: {allowDeliveryOptions: true, allowMorningDelivery: true},
              label: 'settings_carrier_price_delivery_type_morning',
            },
            {
              name: 'allowEveningDelivery',
              $component: 'ToggleInput',
              $visibleWhen: {allowDeliveryOptions: true},
              label: 'settings_carrier_allow_evening_delivery',
            },
            {
              name: 'priceDeliveryTypeEvening',
              $component: 'CurrencyInput',
              $visibleWhen: {allowDeliveryOptions: true, allowEveningDelivery: true},
              label: 'settings_carrier_price_delivery_type_evening',
            },
            {
              name: 'allowSameDayDelivery',
              $component: 'ToggleInput',
              $visibleWhen: {allowDeliveryOptions: true},
              label: 'settings_carrier_allow_same_day_delivery',
            },
            {
              name: 'priceDeliveryTypeSameDay',
              $component: 'CurrencyInput',
              $visibleWhen: {allowDeliveryOptions: true, allowSameDayDelivery: true},
              label: 'settings_carrier_price_delivery_type_same_day',
            },
          ],
        },
      ],
    },
  },

  dynamic: {
    account: {
      id: 126594,
      platformId: 1,
      status: 2,
      contactInfo: {
        boxNumber: '',
        cc: undefined,
        city: '',
        fullStreet: undefined,
        number: '',
        numberSuffix: '',
        postalCode: '',
        region: '',
        state: undefined,
        street: '',
        streetAdditionalInfo: '',
        email: 'edie+backoffice@myparcel.nl',
        phone: '0612345678',
        person: undefined,
        company: undefined,
      },
      generalSettings: {isTest: true, orderMode: true, hasCarrierContract: false},
      shops: [
        {
          id: 86330,
          accountId: 126594,
          platformId: 1,
          name: 'php-sdk-1',
          hidden: false,
          billing: {
            address: {
              cc: 'NL',
              postalCode: '2132 JE',
              city: 'Hoofddorp',
              street: 'Antareslaan',
              number: '31',
              numberSuffix: '',
              person: 'Edie Lemoine',
              company: 'MyParcel',
              email: 'edie@myparcel.nl',
              phone: '0617752983',
              streetAdditionalInfo: '',
            },
            billingMethod: 2,
            vatTariff: 210,
            vatType: 'general',
            iban: 'NL41INGB0003920701',
            vatNumber: 'dgdsg',
            coc: 'sgsdgs',
            bic: 'INGBNL2A',
            sendInvoiceReminders: 0,
            cycle: 'monthly',
          },
          deliveryAddress: {
            cc: 'NL',
            postalCode: '2132 WT',
            city: 'Hoofddorp',
            street: 'Siriusdreef',
            number: '66',
            numberSuffix: '',
            company: 'MyParcel',
            email: 'edie@myparcel.nl',
            phone: '0617752983',
            streetAdditionalInfo: '',
            gender: 'mrs',
            firstName: 'Edie',
            lastName: 'Lemoine',
          },
          generalSettings: {
            weight: 1000,
            labelFormat: 'A4',
            postagePaid: 0,
            reminderEmail: 0,
            useLogoEmail: 0,
            useLogoLabel: 1,
            preferredLocale: 'nl_NL',
            labelDescription: 'standaard kenmerk',
            autoSaveAddresses: 1,
            labelFormatLocked: 0,
            totalShipmentsOnOverview: 10,
            hasSeenDigitalStampPrintNotification: 1,
          },
          return: {
            address: {
              cc: 'NL',
              postalCode: '2132 JE',
              city: 'Hoofddorp',
              street: 'Antareslaan',
              number: '31',
              numberSuffix: '',
              person: 'Edie Lemoine',
              company: 'MyParcel',
              email: 'edie@myparcel.nl',
              phone: '0617752983',
              streetAdditionalInfo: '',
            },
            linkExpiresAfter: 3650,
            useShopShipmentOptions: 0,
            sendTracktraceEmailForReturnShipments: 0,
            useCustomDescription: 0,
            fromAddressName: 'MyParcel',
            bcc: 0,
            emailAddressForTracktraceReturnShipments: undefined,
            contribution: {amount: 0, currency: 'EUR'},
          },
          shipmentOptions: {
            packageType: 1,
            onlyRecipient: 1,
            signature: 1,
            return: 0,
            insurance: {amount: 100000, currency: 'EUR'},
            largeFormat: 0,
            cooledDelivery: 0,
            labelDescription: 'standaard kenmerk',
            ageCheck: 0,
            // saturdayDelivery: 0,
            dropOffAtPostalPoint: 0,
            collect: 0,
            sameDayDelivery: 0,
            printerlessReturn: 0,
            extraAssurance: 0,
            // hideSender: 0,
          },
          trackTrace: [],
          carrierConfigurations: [],
          carrierOptions: [
            {
              carrier: {
                externalIdentifier: 'postnl',
                id: 1,
                name: 'postnl',
                human: undefined,
                subscriptionId: undefined,
                enabled: true,
                isDefault: false,
                label: undefined,
                optional: false,
                primary: true,
                type: 'main',
              },
              capabilities: {
                deliveryTypes: ['morning', 'standard', 'evening', 'pickup'],
                features: {labelDescriptionLength: 45},
                packageTypes: ['package', 'mailbox', 'letter', 'digital_stamp'],
                shipmentOptions: {
                  ageCheck: true,
                  largeFormat: true,
                  onlyRecipient: true,
                  return: true,
                  sameDayDelivery: true,
                  signature: true,
                  insurance: [
                    0, 10000, 25000, 50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000, 450000, 500000,
                  ],
                },
              },
              returnCapabilities: {
                deliveryTypes: ['standard'],
                features: {labelDescriptionLength: 45},
                packageTypes: ['package'],
                shipmentOptions: {
                  signature: true,
                  insurance: [
                    0, 10000, 25000, 50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000, 450000, 500000,
                  ],
                  return: true,
                  ageCheck: true,
                  onlyRecipient: true,
                  sameDayDelivery: true,
                  largeFormat: true,
                },
              },
            },
            {
              carrier: {
                externalIdentifier: 'cheapcargo',
                id: 3,
                name: 'cheapcargo',
                human: undefined,
                subscriptionId: undefined,
                enabled: true,
                isDefault: false,
                label: undefined,
                optional: false,
                primary: true,
                type: 'main',
              },
              capabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
              returnCapabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
            },
            {
              carrier: {
                externalIdentifier: 'dhl',
                id: 6,
                name: 'dhl',
                human: undefined,
                subscriptionId: undefined,
                enabled: true,
                isDefault: false,
                label: undefined,
                optional: true,
                primary: true,
                type: 'main',
              },
              capabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
              returnCapabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
            },
            {
              carrier: {
                externalIdentifier: 'bol.com',
                id: 7,
                name: 'bol.com',
                human: undefined,
                subscriptionId: undefined,
                enabled: true,
                isDefault: false,
                label: undefined,
                optional: false,
                primary: true,
                type: 'main',
              },
              capabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
              returnCapabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
            },
            {
              carrier: {
                externalIdentifier: 'ups',
                id: 8,
                name: 'ups',
                human: undefined,
                subscriptionId: undefined,
                enabled: true,
                isDefault: false,
                label: undefined,
                optional: true,
                primary: true,
                type: 'main',
              },
              capabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
              returnCapabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
            },
            {
              carrier: {
                externalIdentifier: 'dhlforyou',
                id: 9,
                name: 'dhlforyou',
                human: undefined,
                subscriptionId: undefined,
                enabled: true,
                isDefault: false,
                label: undefined,
                optional: true,
                primary: true,
                type: 'main',
              },
              capabilities: {
                deliveryTypes: ['standard', 'pickup'],
                features: {labelDescriptionLength: 45},
                packageTypes: ['package', 'mailbox'],
                shipmentOptions: {
                  ageCheck: true,
                  largeFormat: false,
                  onlyRecipient: true,
                  return: true,
                  sameDayDelivery: true,
                  signature: true,
                  // saturdayDelivery: true,
                  // hideSender: true,
                  insurance: [0, 50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000, 450000, 500000],
                },
              },
              returnCapabilities: {
                deliveryTypes: ['standard'],
                features: {labelDescriptionLength: 45},
                packageTypes: ['package'],
                shipmentOptions: {
                  signature: true,
                  insurance: [0],
                  return: true,
                  ageCheck: true,
                  onlyRecipient: true,
                  sameDayDelivery: true,
                  largeFormat: true,
                },
              },
            },
            {
              carrier: {
                externalIdentifier: 'dhlparcelconnect',
                id: 10,
                name: 'dhlparcelconnect',
                human: undefined,
                subscriptionId: undefined,
                enabled: true,
                isDefault: false,
                label: undefined,
                optional: true,
                primary: true,
                type: 'main',
              },
              capabilities: {
                deliveryTypes: ['standard', 'pickup'],
                features: {labelDescriptionLength: 45},
                packageTypes: ['package'],
                shipmentOptions: {
                  ageCheck: false,
                  onlyRecipient: false,
                  return: false,
                  sameDayDelivery: false,
                  signature: true,
                  // saturdayDelivery: false,
                  // hideSender: false,
                  insurance: [0, 50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000, 450000, 500000],
                },
              },
              returnCapabilities: {
                deliveryTypes: ['standard'],
                features: {labelDescriptionLength: 45},
                packageTypes: ['package'],
                shipmentOptions: {
                  signature: false,
                  insurance: [50000],
                  return: false,
                  ageCheck: false,
                  onlyRecipient: false,
                  sameDayDelivery: false,
                  largeFormat: false,
                },
              },
            },
            {
              carrier: {
                externalIdentifier: 'dhleuroplus',
                id: 11,
                name: 'dhleuroplus',
                human: undefined,
                subscriptionId: undefined,
                enabled: true,
                isDefault: false,
                label: undefined,
                optional: true,
                primary: true,
                type: 'main',
              },
              capabilities: {
                deliveryTypes: ['standard'],
                features: {labelDescriptionLength: 45},
                packageTypes: ['package', 'mailbox'],
                shipmentOptions: {signature: true, insurance: [0, 50000]},
              },
              returnCapabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
            },
          ],
        },
      ],
    },
    carriers: undefined,
    pluginSettings: {
      account: {id: 'account', apiKey: '64c0afe6463444b1b5ec217f33fe227f3d2215ae'},
      general: {
        id: 'general',
        apiLogging: false,
        barcodeInNote: false,
        barcodeInNoteTitle: undefined,
        conceptShipments: false,
        exportWithAutomaticStatus: undefined,
        orderMode: false,
        processDirectly: false,
        shareCustomerInformation: false,
        trackTraceInAccount: true,
        trackTraceInEmail: false,
      },
      order: {
        id: 'order',
        emptyDigitalStampWeight: undefined,
        emptyMailboxWeight: undefined,
        emptyParcelWeight: undefined,
        ignoreOrderStatuses: undefined,
        orderStatusMail: true,
        saveCustomerAddress: false,
        sendNotificationAfter: undefined,
        sendOrderStateForDigitalStamp: true,
        statusOnLabelCreate: 'wc-pending',
        statusWhenDelivered: '-1',
        statusWhenLabelScanned: '-1',
      },
      label: {id: 'label', description: undefined, format: 'A4', output: 'open', position: 1, prompt: false},
      customs: {id: 'customs', countryOfOrigin: undefined, customsCode: '0', packageContents: '1'},
      checkout: {
        id: 'checkout',
        deliveryOptionsCustomCss: undefined,
        deliveryOptionsDisplay: false,
        deliveryOptionsHeader: undefined,
        deliveryOptionsPosition: undefined,
        pickupLocationsDefaultView: 'list',
        priceType: 'included',
        enableDeliveryOptions: true,
        enableDeliveryOptionsWhenNotInStock: true,
        useSeparateAddressFields: false,
      },
      carrier: {
        dhleuroplus: {
          id: 'dhleuroplus',
          carrierName: undefined,
          allowDeliveryOptions: true,
          allowEveningDelivery: true,
          allowMondayDelivery: false,
          allowMorningDelivery: false,
          allowOnlyRecipient: false,
          allowPickupLocations: false,
          allowSameDayDelivery: false,
          allowSaturdayDelivery: false,
          allowSignature: true,
          cutoffTime: undefined,
          cutoffTimeSameDay: undefined,
          defaultPackageType: 'package',
          deliveryDaysWindow: 7,
          deliveryOptionsDisplay: undefined,
          deliveryOptionsEnabledForBackorders: false,
          digitalStampDefaultWeight: 0,
          dropOffDelay: 0,
          dropOffPoint: undefined,
          dropOffPossibilities: {dropOffDays: [], dropOffDaysDeviations: []},
          exportAgeCheck: false,
          exportInsurance: false,
          exportInsuranceFromAmount: 0,
          exportInsuranceUpTo: 0,
          exportInsuranceUpToBe: 0,
          exportInsuranceUpToEu: 0,
          exportLargeFormat: false,
          exportOnlyRecipient: true,
          exportReturnLargeFormat: false,
          exportReturnPackageType: 'package',
          exportReturn: false,
          exportSignature: false,
          priceDeliveryTypeEvening: 0,
          priceDeliveryTypeMonday: 0,
          priceDeliveryTypeMorning: 0,
          priceDeliveryTypeSameDay: 0,
          priceDeliveryTypeStandard: 0,
          priceOnlyRecipient: 0,
          pricePackageTypeDigitalStamp: 0,
          pricePackageTypeMailbox: 0,
          priceDeliveryTypePickup: 0,
          priceSignature: 3,
          shippingMethodPackageTypes: [],
          showDeliveryDay: true,
        },
        postnl: {
          id: 'postnl',
          carrierName: undefined,
          allowDeliveryOptions: true,
          allowEveningDelivery: true,
          allowMondayDelivery: false,
          allowMorningDelivery: false,
          allowOnlyRecipient: false,
          allowPickupLocations: false,
          allowSameDayDelivery: false,
          allowSaturdayDelivery: false,
          allowSignature: true,
          cutoffTime: undefined,
          cutoffTimeSameDay: undefined,
          defaultPackageType: 'package',
          deliveryDaysWindow: 7,
          deliveryOptionsDisplay: undefined,
          deliveryOptionsEnabledForBackorders: false,
          digitalStampDefaultWeight: 0,
          dropOffDelay: 0,
          dropOffPoint: undefined,
          dropOffPossibilities: {dropOffDays: [], dropOffDaysDeviations: []},
          exportAgeCheck: false,
          exportInsurance: false,
          exportInsuranceFromAmount: 0,
          exportInsuranceUpTo: 0,
          exportInsuranceUpToBe: 0,
          exportInsuranceUpToEu: 0,
          exportLargeFormat: true,
          exportOnlyRecipient: true,
          exportReturnLargeFormat: false,
          exportReturnPackageType: 'package',
          exportReturn: false,
          exportSignature: true,
          priceDeliveryTypeEvening: 0,
          priceDeliveryTypeMonday: 0,
          priceDeliveryTypeMorning: 0,
          priceDeliveryTypeSameDay: 0,
          priceDeliveryTypeStandard: 0,
          priceOnlyRecipient: 0,
          pricePackageTypeDigitalStamp: 0,
          pricePackageTypeMailbox: 0,
          priceDeliveryTypePickup: 0,
          priceSignature: 3,
          shippingMethodPackageTypes: [],
          showDeliveryDay: true,
        },
        dhlforyou: {
          id: 'dhlforyou',
          carrierName: undefined,
          allowDeliveryOptions: true,
          allowEveningDelivery: true,
          allowMondayDelivery: false,
          allowMorningDelivery: false,
          allowOnlyRecipient: false,
          allowPickupLocations: false,
          allowSameDayDelivery: false,
          allowSaturdayDelivery: false,
          allowSignature: true,
          cutoffTime: undefined,
          cutoffTimeSameDay: undefined,
          defaultPackageType: 'package',
          deliveryDaysWindow: 7,
          deliveryOptionsDisplay: undefined,
          deliveryOptionsEnabledForBackorders: false,
          digitalStampDefaultWeight: 0,
          dropOffDelay: 0,
          dropOffPoint: undefined,
          dropOffPossibilities: {dropOffDays: [], dropOffDaysDeviations: []},
          exportAgeCheck: false,
          exportInsurance: false,
          exportInsuranceFromAmount: 0,
          exportInsuranceUpTo: 0,
          exportInsuranceUpToBe: 0,
          exportInsuranceUpToEu: 0,
          exportLargeFormat: false,
          exportOnlyRecipient: true,
          exportReturnLargeFormat: false,
          exportReturnPackageType: 'package',
          exportReturn: false,
          exportSignature: false,
          priceDeliveryTypeEvening: 0,
          priceDeliveryTypeMonday: 0,
          priceDeliveryTypeMorning: 0,
          priceDeliveryTypeSameDay: 0,
          priceDeliveryTypeStandard: 0,
          priceOnlyRecipient: 0,
          pricePackageTypeDigitalStamp: 0,
          pricePackageTypeMailbox: 0,
          priceDeliveryTypePickup: 0,
          priceSignature: 3,
          shippingMethodPackageTypes: [],
          showDeliveryDay: true,
        },
        dhlparcelconnect: {
          id: 'dhlparcelconnect',
          carrierName: undefined,
          allowDeliveryOptions: true,
          allowEveningDelivery: true,
          allowMondayDelivery: false,
          allowMorningDelivery: false,
          allowOnlyRecipient: false,
          allowPickupLocations: false,
          allowSameDayDelivery: false,
          allowSaturdayDelivery: false,
          allowSignature: true,
          cutoffTime: undefined,
          cutoffTimeSameDay: undefined,
          defaultPackageType: 'package',
          deliveryDaysWindow: 7,
          deliveryOptionsDisplay: undefined,
          deliveryOptionsEnabledForBackorders: false,
          digitalStampDefaultWeight: 0,
          dropOffDelay: 0,
          dropOffPoint: undefined,
          dropOffPossibilities: {dropOffDays: [], dropOffDaysDeviations: []},
          exportAgeCheck: false,
          exportInsurance: false,
          exportInsuranceFromAmount: 0,
          exportInsuranceUpTo: 0,
          exportInsuranceUpToBe: 0,
          exportInsuranceUpToEu: 0,
          exportLargeFormat: false,
          exportOnlyRecipient: true,
          exportReturnLargeFormat: false,
          exportReturnPackageType: 'package',
          exportReturn: false,
          exportSignature: false,
          priceDeliveryTypeEvening: 0,
          priceDeliveryTypeMonday: 0,
          priceDeliveryTypeMorning: 0,
          priceDeliveryTypeSameDay: 0,
          priceDeliveryTypeStandard: 0,
          priceOnlyRecipient: 0,
          pricePackageTypeDigitalStamp: 0,
          pricePackageTypeMailbox: 0,
          priceDeliveryTypePickup: 0,
          priceSignature: 3,
          shippingMethodPackageTypes: [],
          showDeliveryDay: true,
        },
      },
    },
    printOptionsView: undefined,
    shop: {
      id: 86330,
      accountId: 126594,
      platformId: 1,
      name: 'php-sdk-1',
      hidden: false,
      billing: {
        address: {
          cc: 'NL',
          postalCode: '2132 JE',
          city: 'Hoofddorp',
          street: 'Antareslaan',
          number: '31',
          numberSuffix: '',
          person: 'Edie Lemoine',
          company: 'MyParcel',
          email: 'edie@myparcel.nl',
          phone: '0617752983',
          streetAdditionalInfo: '',
        },
        billingMethod: 2,
        vatTariff: 210,
        vatType: 'general',
        iban: 'NL41INGB0003920701',
        vatNumber: 'dgdsg',
        coc: 'sgsdgs',
        bic: 'INGBNL2A',
        sendInvoiceReminders: 0,
        cycle: 'monthly',
      },
      deliveryAddress: {
        cc: 'NL',
        postalCode: '2132 WT',
        city: 'Hoofddorp',
        street: 'Siriusdreef',
        number: '66',
        numberSuffix: '',
        company: 'MyParcel',
        email: 'edie@myparcel.nl',
        phone: '0617752983',
        streetAdditionalInfo: '',
        gender: 'mrs',
        firstName: 'Edie',
        lastName: 'Lemoine',
      },
      generalSettings: {
        weight: 1000,
        labelFormat: 'A4',
        postagePaid: 0,
        reminderEmail: 0,
        useLogoEmail: 0,
        useLogoLabel: 1,
        preferredLocale: 'nl_NL',
        labelDescription: 'standaard kenmerk',
        autoSaveAddresses: 1,
        labelFormatLocked: 0,
        totalShipmentsOnOverview: 10,
        hasSeenDigitalStampPrintNotification: 1,
      },
      return: {
        address: {
          cc: 'NL',
          postalCode: '2132 JE',
          city: 'Hoofddorp',
          street: 'Antareslaan',
          number: '31',
          numberSuffix: '',
          person: 'Edie Lemoine',
          company: 'MyParcel',
          email: 'edie@myparcel.nl',
          phone: '0617752983',
          streetAdditionalInfo: '',
        },
        linkExpiresAfter: 3650,
        useShopShipmentOptions: 0,
        sendTracktraceEmailForReturnShipments: 0,
        useCustomDescription: 0,
        fromAddressName: 'MyParcel',
        bcc: 0,
        emailAddressForTracktraceReturnShipments: undefined,
        contribution: {amount: 0, currency: 'EUR'},
      },
      shipmentOptions: {
        packageType: 1,
        onlyRecipient: 1,
        signature: 1,
        return: 0,
        insurance: {amount: 100000, currency: 'EUR'},
        largeFormat: 0,
        cooledDelivery: 0,
        labelDescription: 'standaard kenmerk',
        ageCheck: 0,
        // saturdayDelivery: 0,
        dropOffAtPostalPoint: 0,
        collect: 0,
        sameDayDelivery: 0,
        printerlessReturn: 0,
        extraAssurance: 0,
        // hideSender: 0,
      },
      trackTrace: [],
      carrierConfigurations: [
        {
          carrier: 'instabox',
          defaultCutoffTime: undefined,
          defaultDropOffPoint: undefined,
          defaultDropOffPointIdentifier: undefined,
          mondayCutoffTime: undefined,
        },
      ],
      carrierOptions: [
        {
          carrier: {
            externalIdentifier: 'postnl',
            id: 1,
            name: CarrierName.PostNl,
            human: undefined,
            subscriptionId: undefined,
            enabled: true,
            isDefault: false,
            label: undefined,
            optional: false,
            primary: true,
            type: 'main',
          },
          capabilities: {
            deliveryTypes: ['morning', 'standard', 'evening', 'pickup'],
            features: {labelDescriptionLength: 45},
            packageTypes: ['package', 'mailbox', 'letter', 'digital_stamp'],
            shipmentOptions: {
              ageCheck: true,
              largeFormat: true,
              onlyRecipient: true,
              return: true,
              sameDayDelivery: true,
              signature: true,
              insurance: [
                0, 10000, 25000, 50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000, 450000, 500000,
              ],
            },
          },
          returnCapabilities: {
            deliveryTypes: ['standard'],
            features: {labelDescriptionLength: 45},
            packageTypes: ['package'],
            shipmentOptions: {
              signature: true,
              insurance: [
                0, 10000, 25000, 50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000, 450000, 500000,
              ],
              return: true,
              ageCheck: true,
              onlyRecipient: true,
              sameDayDelivery: true,
              largeFormat: true,
            },
          },
        },
        {
          carrier: {
            externalIdentifier: 'cheapcargo',
            id: 3,
            name: CarrierName.CheapCargo,
            human: undefined,
            subscriptionId: undefined,
            enabled: true,
            isDefault: false,
            label: undefined,
            optional: false,
            primary: true,
            type: 'main',
          },
          capabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
          returnCapabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
        },
        {
          carrier: {
            externalIdentifier: 'dhl',
            id: 6,
            name: CarrierName.Dhl,
            human: undefined,
            subscriptionId: undefined,
            enabled: true,
            isDefault: false,
            label: undefined,
            optional: true,
            primary: true,
            type: 'main',
          },
          capabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
          returnCapabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
        },
        {
          carrier: {
            externalIdentifier: 'bol.com',
            id: 7,
            name: CarrierName.BolCom,
            human: undefined,
            subscriptionId: undefined,
            enabled: true,
            isDefault: false,
            label: undefined,
            optional: false,
            primary: true,
            type: 'main',
          },
          capabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
          returnCapabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
        },
        {
          carrier: {
            externalIdentifier: 'ups',
            id: 8,
            name: CarrierName.Ups,
            human: undefined,
            subscriptionId: undefined,
            enabled: true,
            isDefault: false,
            label: undefined,
            optional: true,
            primary: true,
            type: 'main',
          },
          capabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
          returnCapabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
        },
        {
          carrier: {
            externalIdentifier: 'dhlforyou',
            id: 9,
            name: CarrierName.DhlForYou,
            human: undefined,
            subscriptionId: undefined,
            enabled: true,
            isDefault: false,
            label: undefined,
            optional: true,
            primary: true,
            type: 'main',
          },
          capabilities: {
            deliveryTypes: ['standard', 'pickup'],
            features: {labelDescriptionLength: 45},
            packageTypes: ['package', 'mailbox'],
            shipmentOptions: {
              ageCheck: true,
              largeFormat: false,
              onlyRecipient: true,
              return: true,
              sameDayDelivery: true,
              signature: true,
              // saturdayDelivery: true,
              // hideSender: true,
              insurance: [0, 50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000, 450000, 500000],
            },
          },
          returnCapabilities: {
            deliveryTypes: ['standard'],
            features: {labelDescriptionLength: 45},
            packageTypes: ['package'],
            shipmentOptions: {
              signature: true,
              insurance: [0],
              return: true,
              ageCheck: true,
              onlyRecipient: true,
              sameDayDelivery: true,
              largeFormat: true,
            },
          },
        },
        {
          carrier: {
            externalIdentifier: 'dhlparcelconnect',
            id: 10,
            name: CarrierName.DhlParcelConnect,
            human: undefined,
            subscriptionId: undefined,
            enabled: true,
            isDefault: false,
            label: undefined,
            optional: true,
            primary: true,
            type: 'main',
          },
          capabilities: {
            deliveryTypes: ['standard', 'pickup'],
            features: {labelDescriptionLength: 45},
            packageTypes: ['package'],
            shipmentOptions: {
              ageCheck: false,
              onlyRecipient: false,
              return: false,
              sameDayDelivery: false,
              signature: true,
              // saturdayDelivery: false,
              // hideSender: false,
              insurance: [0, 50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000, 450000, 500000],
            },
          },
          returnCapabilities: {
            deliveryTypes: ['standard'],
            features: {labelDescriptionLength: 45},
            packageTypes: ['package'],
            shipmentOptions: {
              signature: false,
              insurance: [50000],
              return: false,
              ageCheck: false,
              onlyRecipient: false,
              sameDayDelivery: false,
              largeFormat: false,
            },
          },
        },
        {
          carrier: {
            externalIdentifier: 'dhleuroplus',
            id: 11,
            name: CarrierName.DhlEuroPlus,
            human: undefined,
            subscriptionId: undefined,
            enabled: true,
            isDefault: false,
            label: undefined,
            optional: true,
            primary: true,
            type: 'main',
          },
          capabilities: {
            deliveryTypes: ['standard'],
            features: {labelDescriptionLength: 45},
            packageTypes: ['package', 'mailbox'],
            shipmentOptions: {signature: true, insurance: [0, 50000]},
          },
          returnCapabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
        },
      ],
    },
    carrierOptions: [
      {
        carrier: {
          externalIdentifier: 'postnl',
          id: 1,
          name: CarrierName.PostNl,
          human: undefined,
          subscriptionId: undefined,
          enabled: true,
          isDefault: false,
          label: undefined,
          optional: false,
          primary: true,
          type: 'main',
        },
        capabilities: {
          deliveryTypes: ['morning', 'standard', 'evening', 'pickup'],
          features: {labelDescriptionLength: 45},
          packageTypes: ['package', 'mailbox', 'letter', 'digital_stamp'],
          shipmentOptions: {
            ageCheck: true,
            largeFormat: true,
            onlyRecipient: true,
            return: true,
            sameDayDelivery: true,
            signature: true,
            insurance: [0, 10000, 25000, 50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000, 450000, 500000],
          },
        },
        returnCapabilities: {
          deliveryTypes: ['standard'],
          features: {labelDescriptionLength: 45},
          packageTypes: ['package'],
          shipmentOptions: {
            signature: true,
            insurance: [0, 10000, 25000, 50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000, 450000, 500000],
            return: true,
            ageCheck: true,
            onlyRecipient: true,
            sameDayDelivery: true,
            largeFormat: true,
          },
        },
      },
      {
        carrier: {
          externalIdentifier: 'dhlforyou',
          id: 9,
          name: CarrierName.DhlForYou,
          human: undefined,
          subscriptionId: undefined,
          enabled: true,
          isDefault: false,
          label: undefined,
          optional: true,
          primary: true,
          type: 'main',
        },
        capabilities: {
          deliveryTypes: ['standard', 'pickup'],
          features: {labelDescriptionLength: 45},
          packageTypes: ['package', 'mailbox'],
          shipmentOptions: {
            ageCheck: true,
            largeFormat: false,
            onlyRecipient: true,
            return: true,
            sameDayDelivery: true,
            signature: true,
            // saturdayDelivery: true,
            // hideSender: true,
            insurance: [0, 50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000, 450000, 500000],
          },
        },
        returnCapabilities: {
          deliveryTypes: ['standard'],
          features: {labelDescriptionLength: 45},
          packageTypes: ['package'],
          shipmentOptions: {
            signature: true,
            insurance: [0],
            return: true,
            ageCheck: true,
            onlyRecipient: true,
            sameDayDelivery: true,
            largeFormat: true,
          },
        },
      },
      {
        carrier: {
          externalIdentifier: 'dhlparcelconnect',
          id: 10,
          name: CarrierName.DhlParcelConnect,
          human: undefined,
          subscriptionId: undefined,
          enabled: true,
          isDefault: false,
          label: undefined,
          optional: true,
          primary: true,
          type: 'main',
        },
        capabilities: {
          deliveryTypes: ['standard', 'pickup'],
          features: {labelDescriptionLength: 45},
          packageTypes: ['package'],
          shipmentOptions: {
            ageCheck: false,
            onlyRecipient: false,
            return: false,
            sameDayDelivery: false,
            signature: true,
            // saturdayDelivery: false,
            // hideSender: false,
            insurance: [0, 50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000, 450000, 500000],
          },
        },
        returnCapabilities: {
          deliveryTypes: ['standard'],
          features: {labelDescriptionLength: 45},
          packageTypes: ['package'],
          shipmentOptions: {
            signature: false,
            insurance: [50000],
            return: false,
            ageCheck: false,
            onlyRecipient: false,
            sameDayDelivery: false,
            largeFormat: false,
          },
        },
      },
      {
        carrier: {
          externalIdentifier: 'dhleuroplus',
          id: 11,
          name: CarrierName.DhlEuroPlus,
          human: undefined,
          subscriptionId: undefined,
          enabled: true,
          isDefault: false,
          label: undefined,
          optional: true,
          primary: true,
          type: 'main',
        },
        capabilities: {
          deliveryTypes: ['standard'],
          features: {labelDescriptionLength: 45},
          packageTypes: ['package', 'mailbox'],
          shipmentOptions: {signature: true, insurance: [0, 50000]},
        },
        returnCapabilities: {deliveryTypes: [], features: {}, packageTypes: [], shipmentOptions: {}},
      },
    ],
  },
};
