/* eslint-disable @typescript-eslint/no-magic-numbers */
import {BackendEndpoint} from '@myparcel-pdk/common/src';
import {PdkContextObject} from '@myparcel-pdk/frontend-core/src';
import translations from './translations/en.json';

export const context: PdkContextObject = {
  orderIdentifier: '',
  global: {
    baseUrl: 'http://localhost',
    bootId: 'myparcel-pdk-boot',
    endpoints: Object.keys(BackendEndpoint).reduce(
      (acc, key) => ({
        ...acc,
        [key]: {
          body: '',
          headers: [],
          method: '',
          parameters: {
            action: key,
          },
          path: '',
          property: '',
        },
      }),
      {} as PdkContextObject['global']['endpoints'],
    ),
    event: '',
    language: 'en',
    mode: 'development',
    pluginSettings: {
      carrier: [],
      order: {
        emptyDigitalStampWeight: 0,
        emptyParcelWeight: 0,
        ignoreOrderStatuses: '',
        orderStatusMail: true,
        saveCustomerAddress: true,
        sendNotificationAfter: 'true',
        sendOrderStateForDigitalStamps: true,
        statusOnLabelCreate: 'true',
        statusWhenDelivered: 'true',
        statusWhenLabelScanned: 'true',
      },
      checkout: {
        deliveryOptionsCustomCss: '',
        deliveryOptionsDisplay: true,
        deliveryOptionsPosition: '',
        pickupLocationsDefaultView: '',
        priceType: '',
        showDeliveryDay: true,
        showPriceAsSurcharge: true,
        useSeparateAddressFields: true,
        stringAddressNotFound: '',
        stringCountry: '',
        stringCity: '',
        stringDelivery: '',
        stringDiscount: '',
        stringEveningDelivery: '',
        stringFrom: '',
        stringHouseNumber: '',
        stringLoadMore: '',
        stringMorningDelivery: '',
        stringOnlyRecipient: '',
        stringOpeningHours: '',
        stringPickupLocationsListButton: '',
        stringPickupLocationsMapButton: '',
        stringPickup: '',
        stringPostalCode: '',
        stringRecipient: '',
        stringRetry: '',
        stringSaturdayDelivery: '',
        stringSignature: '',
        stringStandardDelivery: '',
        stringWrongNumberPostalCode: '',
        stringWrongPostalCodeCity: '',
      },
      customs: {
        countryOfOrigin: 'countryOfOrigin',
        customsCode: 'customsCode',
        packageContents: 'packageContents',
      },
      general: {
        apiKey: '',
        apiLogging: true,
        barcodeInNote: true,
        conceptShipments: true,
        exportWithAutomaticStatus: '',
        orderMode: false,
        processDirectly: true,
        shareCustomerInformation: true,
        trackTraceInAccount: true,
        trackTraceInEmail: true,
      },
      label: {
        description: '',
        format: '',
        output: '',
        position: 1,
        prompt: true,
      },
    },
    translations,
  },

  pluginSettingsView: {
    general: [
      {name: 'apiKey', label: 'settings_general_api_key', type: 'TextInput'},
      {name: 'apiLogging', label: 'settings_general_api_logging', type: 'ToggleInput'},
      {
        name: 'shareCustomerInformation',
        label: 'settings_general_share_customer_information',
        type: 'ToggleInput',
      },
      {name: 'conceptShipments', label: 'settings_general_concept_shipments', type: 'ToggleInput'},
      {name: 'orderMode', label: 'settings_general_order_mode', type: 'ToggleInput'},
      {name: 'trackTraceInEmail', label: 'settings_general_track_trace_in_email', type: 'ToggleInput'},
      {name: 'trackTraceInAccount', label: 'settings_general_track_trace_in_account', type: 'ToggleInput'},
      {name: 'barcodeInNote', label: 'settings_general_barcode_in_note', type: 'ToggleInput'},
      {name: 'processDirectly', label: 'settings_general_process_directly', type: 'ToggleInput'},
    ],
    order: [
      {
        name: 'statusOnLabelCreate',
        label: 'settings_order_status_on_label_create',
        options: [{value: '0', label: 'settings_none'}],
        type: 'SelectInput',
      },
      {
        name: 'statusWhenLabelScanned',
        label: 'settings_order_status_when_label_scanned',
        options: [{value: '0', label: 'settings_none'}],
        type: 'SelectInput',
      },
      {
        name: 'statusWhenDelivered',
        label: 'settings_order_status_when_delivered',
        options: [{value: '0', label: 'settings_none'}],
        type: 'SelectInput',
      },
      {
        name: 'ignoreOrderStatuses',
        label: 'settings_order_ignore_order_statuses',
        options: [{value: '0', label: 'settings_none'}],
        type: 'CheckboxInput',
      },
      {name: 'orderStatusMail', label: 'settings_order_order_status_mail', type: 'ToggleInput'},
      {
        name: 'sendNotificationAfter',
        label: 'settings_order_send_notification_after',
        options: [],
        type: 'SelectInput',
      },
      {
        name: 'sendOrderStateForDigitalStamp',
        label: 'settings_order_send_order_state_for_digital_stamp',
        type: 'ToggleInput',
      },
      {name: 'saveCustomerAddress', label: 'settings_order_save_customer_address', type: 'ToggleInput'},
      {name: 'emptyParcelWeight', label: 'settings_order_empty_parcel_weight', type: 'NumberInput'},
    ],
    label: [
      {
        name: 'description',
        label: 'settings_label_description',
        description: 'settings_label_description_description',
        type: 'TextInput',
      },
      {
        name: 'format',
        label: 'settings_label_format',
        options: [
          {value: 'A4', label: 'settings_label_format_option_a4'},
          {value: 'A6', label: 'settings_label_format_option_a6'},
        ],
        type: 'SelectInput',
      },
      {
        name: 'position',
        label: 'settings_label_position',
        options: [
          {value: 1, label: 'settings_label_position_option_1'},
          {value: 2, label: 'settings_label_position_option_2'},
          {value: 3, label: 'settings_label_position_option_3'},
          {value: 4, label: 'settings_label_position_option_4'},
        ],
        type: 'SelectInput',
      },
      {
        name: 'output',
        label: 'settings_label_output',
        options: [
          {value: 'print', label: 'settings_label_output_option_open'},
          {value: 'download', label: 'settings_label_output_option_download'},
        ],
        type: 'SelectInput',
      },
      {name: 'prompt', label: 'settings_label_prompt', type: 'ToggleInput'},
    ],
    customs: [
      {
        name: 'packageContents',
        label: 'settings_customs_package_contents',
        options: [
          {value: 1, label: 'customs_package_contents_commercial_goods'},
          {value: 2, label: 'customs_package_contents_commercial_samples'},
          {value: 3, label: 'customs_package_contents_documents'},
          {value: 4, label: 'customs_package_contents_gifts'},
          {value: 5, label: 'customs_package_contents_return_shipment'},
        ],
        type: 'SelectInput',
      },
      {name: 'customsCode', label: 'settings_customs_customs_code', type: 'TextInput'},
      {
        name: 'countryOfOrigin',
        label: 'settings_customs_country_of_origin',
        options: [
          {value: 'AC', label: 'AC'},
          {value: 'AD', label: 'AD'},
          {value: 'AE', label: 'AE'},
          {value: 'AF', label: 'AF'},
          {value: 'AG', label: 'AG'},
          {value: 'AI', label: 'AI'},
          {value: 'AL', label: 'AL'},
          {value: 'AM', label: 'AM'},
          {value: 'AN', label: 'AN'},
          {value: 'AO', label: 'AO'},
          {value: 'AQ', label: 'AQ'},
          {value: 'AR', label: 'AR'},
          {value: 'AS', label: 'AS'},
          {value: 'AT', label: 'AT'},
          {value: 'AU', label: 'AU'},
          {value: 'AW', label: 'AW'},
          {value: 'AX', label: 'AX'},
          {value: 'AZ', label: 'AZ'},
          {value: 'BA', label: 'BA'},
          {value: 'BB', label: 'BB'},
          {value: 'BD', label: 'BD'},
          {value: 'BE', label: 'BE'},
          {value: 'BF', label: 'BF'},
          {value: 'BG', label: 'BG'},
          {value: 'BH', label: 'BH'},
          {value: 'BI', label: 'BI'},
          {value: 'BJ', label: 'BJ'},
          {value: 'BL', label: 'BL'},
          {value: 'BM', label: 'BM'},
          {value: 'BN', label: 'BN'},
          {value: 'BO', label: 'BO'},
          {value: 'BQ', label: 'BQ'},
          {value: 'BR', label: 'BR'},
          {value: 'BS', label: 'BS'},
          {value: 'BT', label: 'BT'},
          {value: 'BV', label: 'BV'},
          {value: 'BW', label: 'BW'},
          {value: 'BY', label: 'BY'},
          {value: 'BZ', label: 'BZ'},
          {value: 'CA', label: 'CA'},
          {value: 'CC', label: 'CC'},
          {value: 'CD', label: 'CD'},
          {value: 'CF', label: 'CF'},
          {value: 'CG', label: 'CG'},
          {value: 'CH', label: 'CH'},
          {value: 'CI', label: 'CI'},
          {value: 'CK', label: 'CK'},
          {value: 'CL', label: 'CL'},
          {value: 'CM', label: 'CM'},
          {value: 'CN', label: 'CN'},
          {value: 'CO', label: 'CO'},
          {value: 'CR', label: 'CR'},
          {value: 'CU', label: 'CU'},
          {value: 'CV', label: 'CV'},
          {value: 'CW', label: 'CW'},
          {value: 'CX', label: 'CX'},
          {value: 'CY', label: 'CY'},
          {value: 'CZ', label: 'CZ'},
          {value: 'DE', label: 'DE'},
          {value: 'DG', label: 'DG'},
          {value: 'DJ', label: 'DJ'},
          {value: 'DK', label: 'DK'},
          {value: 'DM', label: 'DM'},
          {value: 'DO', label: 'DO'},
          {value: 'DZ', label: 'DZ'},
          {value: 'EA', label: 'EA'},
          {value: 'EC', label: 'EC'},
          {value: 'EE', label: 'EE'},
          {value: 'EG', label: 'EG'},
          {value: 'EH', label: 'EH'},
          {value: 'ER', label: 'ER'},
          {value: 'ES', label: 'ES'},
          {value: 'ET', label: 'ET'},
          {value: 'EZ', label: 'EZ'},
          {value: 'FI', label: 'FI'},
          {value: 'FJ', label: 'FJ'},
          {value: 'FK', label: 'FK'},
          {value: 'FM', label: 'FM'},
          {value: 'FO', label: 'FO'},
          {value: 'FR', label: 'FR'},
          {value: 'GA', label: 'GA'},
          {value: 'GB', label: 'GB'},
          {value: 'GD', label: 'GD'},
          {value: 'GE', label: 'GE'},
          {value: 'GF', label: 'GF'},
          {value: 'GG', label: 'GG'},
          {value: 'GH', label: 'GH'},
          {value: 'GI', label: 'GI'},
          {value: 'GL', label: 'GL'},
          {value: 'GM', label: 'GM'},
          {value: 'GN', label: 'GN'},
          {value: 'GP', label: 'GP'},
          {value: 'GQ', label: 'GQ'},
          {value: 'GR', label: 'GR'},
          {value: 'GS', label: 'GS'},
          {value: 'GT', label: 'GT'},
          {value: 'GU', label: 'GU'},
          {value: 'GW', label: 'GW'},
          {value: 'GY', label: 'GY'},
          {value: 'HK', label: 'HK'},
          {value: 'HM', label: 'HM'},
          {value: 'HN', label: 'HN'},
          {value: 'HR', label: 'HR'},
          {value: 'HT', label: 'HT'},
          {value: 'HU', label: 'HU'},
          {value: 'IC', label: 'IC'},
          {value: 'ID', label: 'ID'},
          {value: 'IE', label: 'IE'},
          {value: 'IL', label: 'IL'},
          {value: 'IM', label: 'IM'},
          {value: 'IN', label: 'IN'},
          {value: 'IO', label: 'IO'},
          {value: 'IQ', label: 'IQ'},
          {value: 'IR', label: 'IR'},
          {value: 'IS', label: 'IS'},
          {value: 'IT', label: 'IT'},
          {value: 'JE', label: 'JE'},
          {value: 'JM', label: 'JM'},
          {value: 'JO', label: 'JO'},
          {value: 'JP', label: 'JP'},
          {value: 'KE', label: 'KE'},
          {value: 'KG', label: 'KG'},
          {value: 'KH', label: 'KH'},
          {value: 'KI', label: 'KI'},
          {value: 'KM', label: 'KM'},
          {value: 'KN', label: 'KN'},
          {value: 'KP', label: 'KP'},
          {value: 'KR', label: 'KR'},
          {value: 'KW', label: 'KW'},
          {value: 'KY', label: 'KY'},
          {value: 'KZ', label: 'KZ'},
          {value: 'LA', label: 'LA'},
          {value: 'LB', label: 'LB'},
          {value: 'LC', label: 'LC'},
          {value: 'LI', label: 'LI'},
          {value: 'LK', label: 'LK'},
          {value: 'LR', label: 'LR'},
          {value: 'LS', label: 'LS'},
          {value: 'LT', label: 'LT'},
          {value: 'LU', label: 'LU'},
          {value: 'LV', label: 'LV'},
          {value: 'LY', label: 'LY'},
          {value: 'MA', label: 'MA'},
          {value: 'MC', label: 'MC'},
          {value: 'MD', label: 'MD'},
          {value: 'ME', label: 'ME'},
          {value: 'MF', label: 'MF'},
          {value: 'MG', label: 'MG'},
          {value: 'MH', label: 'MH'},
          {value: 'MK', label: 'MK'},
          {value: 'ML', label: 'ML'},
          {value: 'MM', label: 'MM'},
          {value: 'MN', label: 'MN'},
          {value: 'MO', label: 'MO'},
          {value: 'MP', label: 'MP'},
          {value: 'MQ', label: 'MQ'},
          {value: 'MR', label: 'MR'},
          {value: 'MS', label: 'MS'},
          {value: 'MT', label: 'MT'},
          {value: 'MU', label: 'MU'},
          {value: 'MV', label: 'MV'},
          {value: 'MW', label: 'MW'},
          {value: 'MX', label: 'MX'},
          {value: 'MY', label: 'MY'},
          {value: 'MZ', label: 'MZ'},
          {value: 'NA', label: 'NA'},
          {value: 'NC', label: 'NC'},
          {value: 'NE', label: 'NE'},
          {value: 'NF', label: 'NF'},
          {value: 'NG', label: 'NG'},
          {value: 'NI', label: 'NI'},
          {value: 'NL', label: 'NL'},
          {value: 'NO', label: 'NO'},
          {value: 'NP', label: 'NP'},
          {value: 'NR', label: 'NR'},
          {value: 'NU', label: 'NU'},
          {value: 'NZ', label: 'NZ'},
          {value: 'OM', label: 'OM'},
          {value: 'PA', label: 'PA'},
          {value: 'PE', label: 'PE'},
          {value: 'PF', label: 'PF'},
          {value: 'PG', label: 'PG'},
          {value: 'PH', label: 'PH'},
          {value: 'PK', label: 'PK'},
          {value: 'PL', label: 'PL'},
          {value: 'PM', label: 'PM'},
          {value: 'PN', label: 'PN'},
          {value: 'PR', label: 'PR'},
          {value: 'PS', label: 'PS'},
          {value: 'PT', label: 'PT'},
          {value: 'PW', label: 'PW'},
          {value: 'PY', label: 'PY'},
          {value: 'QA', label: 'QA'},
          {value: 'RE', label: 'RE'},
          {value: 'RO', label: 'RO'},
          {value: 'RS', label: 'RS'},
          {value: 'RU', label: 'RU'},
          {value: 'RW', label: 'RW'},
          {value: 'SA', label: 'SA'},
          {value: 'SB', label: 'SB'},
          {value: 'SC', label: 'SC'},
          {value: 'SD', label: 'SD'},
          {value: 'SE', label: 'SE'},
          {value: 'SG', label: 'SG'},
          {value: 'SH', label: 'SH'},
          {value: 'SI', label: 'SI'},
          {value: 'SJ', label: 'SJ'},
          {value: 'SK', label: 'SK'},
          {value: 'SL', label: 'SL'},
          {value: 'SM', label: 'SM'},
          {value: 'SN', label: 'SN'},
          {value: 'SO', label: 'SO'},
          {value: 'SR', label: 'SR'},
          {value: 'SS', label: 'SS'},
          {value: 'ST', label: 'ST'},
          {value: 'SV', label: 'SV'},
          {value: 'SX', label: 'SX'},
          {value: 'SY', label: 'SY'},
          {value: 'SZ', label: 'SZ'},
          {value: 'TA', label: 'TA'},
          {value: 'TC', label: 'TC'},
          {value: 'TD', label: 'TD'},
          {value: 'TF', label: 'TF'},
          {value: 'TG', label: 'TG'},
          {value: 'TH', label: 'TH'},
          {value: 'TJ', label: 'TJ'},
          {value: 'TK', label: 'TK'},
          {value: 'TL', label: 'TL'},
          {value: 'TM', label: 'TM'},
          {value: 'TN', label: 'TN'},
          {value: 'TO', label: 'TO'},
          {value: 'TR', label: 'TR'},
          {value: 'TT', label: 'TT'},
          {value: 'TV', label: 'TV'},
          {value: 'TW', label: 'TW'},
          {value: 'TZ', label: 'TZ'},
          {value: 'UA', label: 'UA'},
          {value: 'UG', label: 'UG'},
          {value: 'UM', label: 'UM'},
          {value: 'US', label: 'US'},
          {value: 'UY', label: 'UY'},
          {value: 'UZ', label: 'UZ'},
          {value: 'VA', label: 'VA'},
          {value: 'VC', label: 'VC'},
          {value: 'VE', label: 'VE'},
          {value: 'VG', label: 'VG'},
          {value: 'VI', label: 'VI'},
          {value: 'VN', label: 'VN'},
          {value: 'VU', label: 'VU'},
          {value: 'WF', label: 'WF'},
          {value: 'WS', label: 'WS'},
          {value: 'XC', label: 'XC'},
          {value: 'XK', label: 'XK'},
          {value: 'XL', label: 'XL'},
          {value: 'XM', label: 'XM'},
          {value: 'YE', label: 'YE'},
          {value: 'YT', label: 'YT'},
          {value: 'ZA', label: 'ZA'},
          {value: 'ZM', label: 'ZM'},
          {value: 'ZW', label: 'ZW'},
        ],
        type: 'SelectInput',
      },
    ],
    checkout: [
      {
        name: 'useSeparateAddressFields',
        label: 'settings_checkout_use_separate_address_fields',
        type: 'ToggleInput',
      },
      {
        name: 'priceType',
        label: 'settings_checkout_price_type',
        options: [
          {value: 'included', label: 'settings_checkout_price_type_option_included'},
          {value: 'excluded', label: 'settings_checkout_price_type_option_excluded'},
        ],
        type: 'SelectInput',
      },
      {name: 'showDeliveryDay', label: 'settings_checkout_show_delivery_day', type: 'ToggleInput'},
      {
        name: 'stringDelivery',
        label: 'settings_checkout_string_delivery',
        description: 'settings_checkout_string_delivery_description',
        type: 'TextInput',
      },
      {
        name: 'stringStandardDelivery',
        label: 'settings_checkout_string_standard_delivery',
        description: 'settings_checkout_string_standard_delivery_description',
        type: 'TextInput',
      },
      {
        name: 'stringMorningDelivery',
        label: 'settings_checkout_string_morning_delivery',
        description: 'settings_checkout_string_standard_delivery_description',
        type: 'TextInput',
      },
      {
        name: 'stringEveningDelivery',
        label: 'settings_checkout_string_evening_delivery',
        description: 'settings_checkout_string_standard_delivery_description',
        type: 'TextInput',
      },
      {
        name: 'stringSaturdayDelivery',
        label: 'settings_checkout_string_saturday_delivery',
        description: 'settings_checkout_string_standard_delivery_description',
        type: 'TextInput',
      },
      {name: 'stringSignature', label: 'settings_checkout_string_signature', type: 'TextInput'},
      {name: 'stringOnlyRecipient', label: 'settings_checkout_string_only_recipient', type: 'TextInput'},
      {name: 'stringPickup', label: 'settings_checkout_string_pickup', type: 'TextInput'},
      {name: 'stringHouseNumber', label: 'settings_checkout_string_house_number', type: 'TextInput'},
      {name: 'stringCity', label: 'settings_checkout_string_city', type: 'TextInput'},
      {name: 'stringPostalCode', label: 'settings_checkout_string_postal_code', type: 'TextInput'},
      {name: 'stringCountry', label: 'settings_checkout_string_country', type: 'TextInput'},
      {name: 'stringOpeningHours', label: 'settings_checkout_string_opening_hours', type: 'TextInput'},
      {name: 'stringLoadMore', label: 'settings_checkout_string_load_more', type: 'TextInput'},
      {
        name: 'stringPickupLocationsMapButton',
        label: 'settings_checkout_string_pickup_locations_map_button',
        type: 'TextInput',
      },
      {
        name: 'stringPickupLocationsListButton',
        label: 'settings_checkout_string_pickup_locations_list_button',
        type: 'TextInput',
      },
      {name: 'stringRetry', label: 'settings_checkout_string_retry', type: 'TextInput'},
      {name: 'stringAddressNotFound', label: 'settings_checkout_string_address_not_found', type: 'TextInput'},
      {
        name: 'stringWrongPostalCodeCity',
        label: 'settings_checkout_string_wrong_postal_code_city',
        type: 'TextInput',
      },
      {
        name: 'stringWrongNumberPostalCode',
        label: 'settings_checkout_string_wrong_number_postal_code',
        type: 'TextInput',
      },
      {name: 'stringFrom', label: 'settings_checkout_string_from', type: 'TextInput'},
      {name: 'stringDiscount', label: 'settings_checkout_string_discount', type: 'TextInput'},
    ],
    carrier: [
      {name: 'allowDeliveryOptions', label: 'settings_carrier_allow_delivery_options', type: 'ToggleInput'},
      {name: 'allowEveningDelivery', label: 'settings_carrier_allow_evening_delivery', type: 'ToggleInput'},
      {
        name: 'allowMondayDelivery',
        label: 'settings_carrier_allow_monday_delivery',
        description: 'settings_carrier_allow_monday_delivery_description',
        type: 'ToggleInput',
      },
      {name: 'allowMorningDelivery', label: 'settings_carrier_allow_morning_delivery', type: 'ToggleInput'},
      {name: 'allowOnlyRecipient', label: 'settings_carrier_allow_only_recipient', type: 'ToggleInput'},
      {name: 'allowPickupLocations', label: 'settings_carrier_allow_pickup_locations', type: 'ToggleInput'},
      {name: 'allowSameDayDelivery', label: 'settings_carrier_allow_same_day_delivery', type: 'ToggleInput'},
      {name: 'allowSaturdayDelivery', label: 'settings_carrier_allow_saturday_delivery', type: 'ToggleInput'},
      {name: 'allowSignature', label: 'settings_carrier_allow_signature', type: 'ToggleInput'},
      {name: 'dropOffPossibilities', label: 'settings_carrier_drop_off_days', type: 'DropOffDaySelectInput'},
      {
        name: 'featureShowDeliveryDate',
        label: 'settings_carrier_feature_show_delivery_date',
        type: 'ToggleInput',
      },
      {name: 'priceEveningDelivery', label: 'settings_carrier_price_evening_delivery', type: 'CurrencyInput'},
      {name: 'priceMorningDelivery', label: 'settings_carrier_price_morning_delivery', type: 'CurrencyInput'},
      {name: 'priceOnlyRecipient', label: 'settings_carrier_price_only_recipient', type: 'CurrencyInput'},
      {
        name: 'pricePackageTypeDigitalStamp',
        label: 'settings_carrier_price_package_type_digital_stamp',
        type: 'CurrencyInput',
      },
      {
        name: 'pricePackageTypeMailbox',
        label: 'settings_carrier_price_package_type_mailbox',
        type: 'CurrencyInput',
      },
      {name: 'pricePickup', label: 'settings_carrier_price_pickup', type: 'CurrencyInput'},
      {name: 'priceSameDayDelivery', label: 'settings_carrier_price_same_day_delivery', type: 'CurrencyInput'},
      {name: 'priceSignature', label: 'settings_carrier_price_signature', type: 'CurrencyInput'},
      {name: 'priceStandardDelivery', label: 'settings_carrier_price_standard_delivery', type: 'CurrencyInput'},
      {name: 'defaultPackageType', label: 'settings_carrier_default_package_type', type: 'SelectInput'},
      {name: 'exportAgeCheck', label: 'settings_carrier_export_age_check', type: 'ToggleInput'},
      {name: 'exportInsurance', label: 'settings_carrier_export_insurance', type: 'ToggleInput'},
      {name: 'exportInsuranceAmount', label: 'settings_carrier_export_insurance_amount', type: 'TextInput'},
      {name: 'exportInsuranceUpTo', label: 'settings_carrier_export_insurance_up_to', type: 'SelectInput'},
      {name: 'allowInsuranceBelgium', label: 'settings_carrier_allow_insurance_belgium', type: 'ToggleInput'},
      {name: 'exportLargeFormat', label: 'settings_carrier_export_large_format', type: 'ToggleInput'},
      {name: 'exportOnlyRecipient', label: 'settings_carrier_export_only_recipient', type: 'ToggleInput'},
      {name: 'exportReturnShipments', label: 'settings_carrier_export_return_shipments', type: 'ToggleInput'},
      {name: 'exportSignature', label: 'settings_carrier_export_signature', type: 'ToggleInput'},
      {
        name: 'digitalStampDefaultWeight',
        label: 'settings_carrier_digital_stamp_default_weight',
        type: 'SelectInput',
      },
    ],
  },
};
