import {
  DefaultButton,
  DefaultButtonGroup,
  DefaultCard,
  DefaultCheckboxInput,
  DefaultCol,
  DefaultCurrencyInput,
  DefaultDropdownButton,
  DefaultFormGroup,
  DefaultHeading,
  DefaultIcon,
  DefaultImage,
  DefaultLink,
  DefaultModal,
  DefaultMultiCheckbox,
  DefaultMultiRadio,
  DefaultNotification,
  DefaultNumberInput,
  DefaultPluginSettingsWrapper,
  DefaultRadioInput,
  DefaultRow,
  DefaultSelectInput,
  DefaultTabNavButton,
  DefaultTabNavContentWrapper,
  DefaultTable,
  DefaultTableCol,
  DefaultTableRow,
  DefaultTextInput,
  DefaultToggleInput,
} from '../components';
import {executePdkComponentTests} from '@myparcel/pdk-component-tests';

executePdkComponentTests({
  PdkButton: DefaultButton,
  PdkButtonGroup: DefaultButtonGroup,
  PdkCard: DefaultCard,
  PdkCheckboxInput: DefaultCheckboxInput,
  PdkCol: DefaultCol,
  PdkCurrencyInput: DefaultCurrencyInput,
  PdkDropdownButton: DefaultDropdownButton,
  PdkFormGroup: DefaultFormGroup,
  PdkHeading: DefaultHeading,
  PdkIcon: DefaultIcon,
  PdkImage: DefaultImage,
  PdkLink: DefaultLink,
  PdkModal: DefaultModal,
  PdkMultiCheckbox: DefaultMultiCheckbox,
  PdkMultiRadio: DefaultMultiRadio,
  PdkNotification: DefaultNotification,
  PdkNumberInput: DefaultNumberInput,
  PdkPluginSettingsWrapper: DefaultPluginSettingsWrapper,
  PdkRadioInput: DefaultRadioInput,
  PdkRow: DefaultRow,
  PdkSelectInput: DefaultSelectInput,
  PdkTabNavButton: DefaultTabNavButton,
  PdkTabNavContentWrapper: DefaultTabNavContentWrapper,
  PdkTable: DefaultTable,
  PdkTableCol: DefaultTableCol,
  PdkTableRow: DefaultTableRow,
  PdkTextInput: DefaultTextInput,
  PdkToggleInput: DefaultToggleInput,
});
