import {executePdkComponentTests} from '@myparcel-pdk/admin-component-tests';
import {
  Bootstrap4Box,
  Bootstrap4Button,
  Bootstrap4ButtonGroup,
  Bootstrap4CheckboxInput,
  Bootstrap4Col,
  Bootstrap4DropdownButton,
  Bootstrap4FormGroup,
  Bootstrap4Image,
  Bootstrap4Modal,
  Bootstrap4Notification,
  Bootstrap4RadioInput,
  Bootstrap4Row,
  Bootstrap4SelectInput,
  Bootstrap4Table,
  Bootstrap4TextArea,
  Bootstrap4TextInput,
  Bootstrap4Badge,
} from '../components';

executePdkComponentTests({
  Badge: Bootstrap4Badge,
  Box: Bootstrap4Box,
  Button: Bootstrap4Button,
  ButtonGroup: Bootstrap4ButtonGroup,
  CheckboxInput: Bootstrap4CheckboxInput,
  Col: Bootstrap4Col,
  DropdownButton: Bootstrap4DropdownButton,
  FormGroup: Bootstrap4FormGroup,
  Image: Bootstrap4Image,
  Modal: Bootstrap4Modal,
  Notification: Bootstrap4Notification,
  RadioInput: Bootstrap4RadioInput,
  Row: Bootstrap4Row,
  SelectInput: Bootstrap4SelectInput,
  Table: Bootstrap4Table,
  TextArea: Bootstrap4TextArea,
  TextInput: Bootstrap4TextInput,
});
