import {executePdkComponentTests} from '@myparcel-pdk/admin-component-tests';
import {AdminComponent} from '@myparcel-pdk/admin';
import {
  Bootstrap4Badge,
  Bootstrap4Box,
  Bootstrap4Button,
  Bootstrap4ButtonGroup,
  Bootstrap4CheckboxInput,
  Bootstrap4Col,
  Bootstrap4DropdownButton,
  Bootstrap4FormGroup,
  Bootstrap4Image,
  Bootstrap4Loader,
  Bootstrap4Modal,
  Bootstrap4Notification,
  Bootstrap4RadioInput,
  Bootstrap4Row,
  Bootstrap4SelectInput,
  Bootstrap4ShipmentLabelWrapper,
  Bootstrap4Table,
  Bootstrap4TextArea,
  Bootstrap4TextInput,
} from '../components';

executePdkComponentTests({
  [AdminComponent.Badge]: Bootstrap4Badge,
  [AdminComponent.Box]: Bootstrap4Box,
  [AdminComponent.ButtonGroup]: Bootstrap4ButtonGroup,
  [AdminComponent.Button]: Bootstrap4Button,
  [AdminComponent.CheckboxInput]: Bootstrap4CheckboxInput,
  [AdminComponent.Col]: Bootstrap4Col,
  [AdminComponent.DropdownButton]: Bootstrap4DropdownButton,
  [AdminComponent.FormGroup]: Bootstrap4FormGroup,
  [AdminComponent.Image]: Bootstrap4Image,
  [AdminComponent.Loader]: Bootstrap4Loader,
  [AdminComponent.Modal]: Bootstrap4Modal,
  [AdminComponent.Notification]: Bootstrap4Notification,
  [AdminComponent.RadioInput]: Bootstrap4RadioInput,
  [AdminComponent.Row]: Bootstrap4Row,
  [AdminComponent.SelectInput]: Bootstrap4SelectInput,
  [AdminComponent.ShipmentLabelWrapper]: Bootstrap4ShipmentLabelWrapper,
  [AdminComponent.Table]: Bootstrap4Table,
  [AdminComponent.TextArea]: Bootstrap4TextArea,
  [AdminComponent.TextInput]: Bootstrap4TextInput,
});
