import {executePdkComponentTests} from '@myparcel-dev/pdk-admin-component-tests';
import {
  DemoBadge,
  DemoBox,
  DemoButton,
  DemoDropdownButton,
  DemoFormGroup,
  DemoImage,
  DemoModal,
  DemoNotification,
  DemoPluginSettingsWrapper,
  DemoRow,
  DemoSelectInput,
  DemoTable,
  DemoTabNavButton,
  DemoTextInput,
  DemoToggleInput,
  DemoTriStateInput,
} from '../components';

executePdkComponentTests({
  Badge: DemoBadge,
  Box: DemoBox,
  Button: DemoButton,
  DropdownButton: DemoDropdownButton,
  FormGroup: DemoFormGroup,
  Image: DemoImage,
  Modal: DemoModal,
  Notification: DemoNotification,
  PluginSettingsWrapper: DemoPluginSettingsWrapper,
  Row: DemoRow,
  SelectInput: DemoSelectInput,
  TabNavButton: DemoTabNavButton,
  Table: DemoTable,
  TextInput: DemoTextInput,
  ToggleInput: DemoToggleInput,
  TriStateInput: DemoTriStateInput,
});
