import {
  DemoButton,
  DemoButtonGroup,
  DemoCard,
  DemoCheckboxInput,
  DemoCol,
  DemoCurrencyInput,
  DemoDropdownButton,
  DemoFormGroup,
  DemoIcon,
  DemoImage,
  DemoLink,
  DemoModal,
  DemoMultiCheckbox,
  DemoMultiRadio,
  DemoNotification,
  DemoNumberInput,
  DemoPluginSettingsWrapper,
  DemoRadioInput,
  DemoRow,
  DemoSelectInput,
  DemoTabNavButton,
  DemoTabNavButtonWrapper,
  DemoTabNavContentWrapper,
  DemoTable,
  DemoTableCol,
  DemoTableRow,
  DemoTextInput,
  DemoToggleInput,
} from '../components';
import {executePdkComponentTests} from '@myparcel-pdk/admin-component-tests';

executePdkComponentTests({
  PdkButton: DemoButton,
  PdkButtonGroup: DemoButtonGroup,
  PdkCard: DemoCard,
  PdkCheckboxInput: DemoCheckboxInput,
  PdkCol: DemoCol,
  PdkCurrencyInput: DemoCurrencyInput,
  PdkDropdownButton: DemoDropdownButton,
  PdkFormGroup: DemoFormGroup,
  PdkIcon: DemoIcon,
  PdkImage: DemoImage,
  PdkLink: DemoLink,
  PdkModal: DemoModal,
  PdkMultiCheckbox: DemoMultiCheckbox,
  PdkMultiRadio: DemoMultiRadio,
  PdkNotification: DemoNotification,
  PdkNumberInput: DemoNumberInput,
  PdkPluginSettingsWrapper: DemoPluginSettingsWrapper,
  PdkRadioInput: DemoRadioInput,
  PdkRow: DemoRow,
  PdkSelectInput: DemoSelectInput,
  PdkTabNavButton: DemoTabNavButton,
  PdkTabNavButtonWrapper: DemoTabNavButtonWrapper,
  PdkTabNavContentWrapper: DemoTabNavContentWrapper,
  PdkTable: DemoTable,
  PdkTableCol: DemoTableCol,
  PdkTableRow: DemoTableRow,
  PdkTextInput: DemoTextInput,
  PdkToggleInput: DemoToggleInput,
});
