import {
  runActionContainerWrapper,
  runButtonGroupTest,
  runButtonTest,
  runCheckboxInputTest,
  runColTest,
  runCurrencyInputTest,
  runDropDownButtonTest,
  runFormGroupTest,
  runHeadingTest,
  runIconTest,
  runImageTest,
  runLinkTest,
  runModalTest,
  runMultiCheckboxTest,
  runMultiRadioTest,
  runNotificationTest,
  runNumberInputTest,
  runPluginSettingsWrapperTest,
  runRadioInputTest,
  runRowTest,
  runSelectInputTest,
  runTabNavButtonTest,
  runTabNavButtonWrapperTest,
  runTabNavContentWrapperTest,
  runTableColTest,
  runTableRowTest,
  runTableTest,
  runTextInputTest,
  runToggleInputTest,
} from '../components';
import {ComponentTest} from '../types';
import {PdkComponentName} from '@myparcel-pdk/common';

export const testMap: Record<PdkComponentName, ComponentTest> = {
  PdkButton: runButtonTest,
  PdkButtonGroup: runButtonGroupTest,
  PdkCard: runActionContainerWrapper,
  PdkCheckboxInput: runCheckboxInputTest,
  PdkCol: runColTest,
  PdkConceptCardWrapper: runActionContainerWrapper,
  PdkCurrencyInput: runCurrencyInputTest,
  PdkDropdownButton: runDropDownButtonTest,
  PdkFormGroup: runFormGroupTest,
  PdkHeading: runHeadingTest,
  PdkIcon: runIconTest,
  PdkImage: runImageTest,
  PdkLink: runLinkTest,
  PdkModal: runModalTest,
  PdkMultiCheckbox: runMultiCheckboxTest,
  PdkMultiRadio: runMultiRadioTest,
  PdkNotification: runNotificationTest,
  PdkNumberInput: runNumberInputTest,
  PdkPluginSettingsWrapper: runPluginSettingsWrapperTest,
  PdkRadioInput: runRadioInputTest,
  PdkRow: runRowTest,
  PdkSelectInput: runSelectInputTest,
  PdkTabNavButton: runTabNavButtonTest,
  PdkTabNavButtonWrapper: runTabNavButtonWrapperTest,
  PdkTabNavContentWrapper: runTabNavContentWrapperTest,
  PdkTable: runTableTest,
  PdkTableCol: runTableColTest,
  PdkTableRow: runTableRowTest,
  PdkTextInput: runTextInputTest,
  PdkToggleInput: runToggleInputTest,
};
