name: 'Run tests 🧪'

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    name: 'Run unit tests 🧪'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: 'Fetch base branch'
        run: git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}

      - uses: ./.github/actions/setup

      - name: 'Run tests'
        run: |
          nx affected \
            --parallel \
            --head=HEAD \
            --base=${{ github.base_ref }} \
            --target=test:run \
            --output-style=static

      - uses: codecov/codecov-action@v3
        continue-on-error: true

      - uses: codacy/codacy-coverage-reporter-action@v1
        continue-on-error: true
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
