name: 'Run tests 🧪'

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/--test.yml
    secrets: inherit
