name: 'Run tests 🧪'

on:
  pull_request:
    branches:
      - main

  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: 'Run unit tests 🧪'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: 'Fetch base branch'
        run: git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}

      - uses: ./.github/actions/setup

      - uses: myparcelnl/actions/bundlewatch@v3
        with:
          token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}

      - name: 'Run tests'
        run: |
          nx affected \
            --parallel \
            --head=HEAD \
            --base=${{ github.base_ref }} \
            --target=test:run \
            --output-style=static

      - name: 'Upload coverage artifact'
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: |
            apps/**/coverage/clover.xml
            libs/**/coverage/clover.xml

  coverage:
    name: 'Upload coverage reports 📊'
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: coverage

      - uses: codecov/codecov-action@v3
        continue-on-error: true

      - uses: codacy/codacy-coverage-reporter-action@v1
        continue-on-error: true
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
