name: 'Run tests 🧪'

on:
  pull_request:
    branches:
      - main
      - beta
      - alpha

  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  bundlewatch:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/install

      - uses: ./.github/actions/build

      - uses: myparcelnl/actions/setup-git-credentials@v3
        id: credentials
        with:
          app-id: ${{ inputs.app-id }}
          private-key: ${{ inputs.private-key }}

      - name: 'Fetch base branch'
        shell: bash
        run: git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}

      - uses: myparcelnl/actions/bundlewatch@v3
        with:
          token: ${{ inputs.bundlewatch-token }}
