name: 'Run tests 🧪'

on:
  pull_request:
    branches:
      - main
      - beta
      - alpha

  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  bundlewatch:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: myparcelnl/actions/yarn-install@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - uses: myparcelnl/actions/nx-run-many@v4
        env:
          NX_BRANCH: production
        with:
          prefix: 'yarn'
          target: 'build'
          args: '--runner=cloud'

      - uses: myparcelnl/actions/setup-git-credentials@v4
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - name: 'Fetch base branch'
        shell: bash
        run: git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}

      - uses: myparcelnl/actions/bundlewatch@v4
        with:
          token: ${{ inputs.bundlewatch-token }}
