name: 'Run tests 🧪'

on:
  pull_request:
    branches:
      - main

  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: 'Run unit tests 🧪'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: 'Fetch base branch'
        run: git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}

      - uses: ./.github/actions/test
        with:
          bundlewatch-token: ${{ secrets.GH_REPO_TOKEN }}
          codacy-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
