name: 'Publish new release 🚀'

on:
  push:
    branches:
      - 'main'
      - 'alpha'
      - 'beta'
      - '*.x'

jobs:
  release:
    uses: myparcelnl/actions/.github/workflows/semantic-release.yml@v2
