name: 'Run tests'

on:
  workflow_call:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: myparcelnl/actions/yarn-install@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: 'Run tests'
        shell: bash
        env:
          NX_BRANCH: ${{ github.event.inputs.branch || github.head_ref || github.ref }}
        #language=bash
        run: |
          yarn nx run-many \
            --runner=cloud \
            --parallel=1 \
            --target=test:coverage \
            --output-style=static

      - name: 'Rename coverage files'
        shell: bash
        #language=bash
        run: |
          yarn workspaces foreach -Apv \
            --exclude=. \
            exec \
            bash -c 'if [ -f coverage/clover.xml ]; then mv coverage/clover.xml coverage/${npm_package_name//\//-}.xml; fi' -- {}

      - uses: codecov/codecov-action@v4
        with:
          files: coverage/*.xml
          flags: unit
          token: ${{ secrets.CODECOV_TOKEN }}
