name: 'Run tests'

on:
  workflow_call:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: myparcelnl/actions/yarn-install@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - uses: myparcelnl/actions/nx-run-many@v4
        env:
          NX_BRANCH: ${{ github.event.inputs.branch || github.head_ref || github.ref }}
        with:
          target: 'test:coverage'
          parallel: 1

      - uses: myparcelnl/actions/collect-test-results@v4

      - uses: myparcelnl/actions/codecov-coverage@v4
        with:
          files: coverage/*.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: myparcelnl/actions/codecov-test-results@v4
        with:
          files: junit/*.xml
          token: ${{ secrets.CODECOV_TOKEN }}
