name: 'Run tests'

on:
  workflow_call:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: myparcelnl/actions/yarn-install@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - uses: myparcelnl/actions/nx-run-many@v4
        env:
          NX_BRANCH: ${{ github.event.inputs.branch || github.head_ref || github.ref }}
        with:
          target: 'test:coverage'
          parallel: 1

      - name: 'Rename coverage files'
        shell: bash
        #language=bash
        run: |
          mkdir -p coverage junit

          yarn workspaces foreach -Apv --exclude=. exec \
            bash -c \
              'if [ -f "coverage/clover.xml" ]; then \
                cp -f "coverage/clover.xml" "'$PWD'/coverage/$(basename $PWD).xml"; \
               fi; \
               if [[ -f "junit.xml" && -s "junit.xml" ]]; then \
                 sed -i "" "s|<testsuites name=\".*\">|<testsuites name=\"${npm_package_name}\">|" "junit.xml"; \
                 cp -f "junit.xml" "'$PWD'/junit/$(basename $PWD).xml"; \
               fi'

      - uses: myparcelnl/actions/codecov-coverage@v4
        with:
          files: coverage/*.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: myparcelnl/actions/codecov-test-results@v4
        with:
          files: junit/*.xml
          token: ${{ secrets.CODECOV_TOKEN }}
