name: 'Run tests'

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/install

      - uses: ./.github/actions/build

      - name: 'Run tests'
        shell: bash
        run: |
          NX_BRANCH=production yarn nx run-many \
            --parallel \
            --target=test:coverage \
            --output-style=static

      - uses: codecov/codecov-action@v3
        continue-on-error: true
