name: 'Run tests'

on:
  workflow_call:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/install

      - uses: ./.github/actions/build

      - name: 'Run tests'
        shell: bash
        env:
          NX_BRANCH: ${{ github.event.inputs.branch || github.head_ref || github.ref }}
        run: |
          yarn nx run-many \
            --runner=cloud \
            --parallel=1 \
            --target=test:coverage \
            --output-style=static

      - name: 'Gather coverage files'
        shell: bash
        run: |
          yarn workspaces foreach -pv \
            --exclude='@myparcel-pdk/monorepo' \
            exec \
            bash -c 'if [ -f coverage/clover.xml ]; then mv coverage/clover.xml coverage/${npm_package_name//\//-}.xml; fi' -- {}

          mkdir -p coverage
          find apps libs -type f -path '*/coverage/*.xml' -exec cp {} coverage \;

      - uses: codecov/codecov-action@v3
        with:
          files: coverage/*.xml
          flags: unit
