name: 'Run tests 🧪'

on:
  workflow_call:

jobs:
  unit:
    name: 'Run unit tests'
    runs-on: ubuntu-20.04
    steps:
      - run: actions/checkout@v3

      - uses: myparcelnl/actions/pnpm-install@v2

      - run: |
          pnpm run test:unit
